export type Language = 'en' | 'hi' | 'mr';

export const LANGUAGE_LABELS: Record<Language, string> = {
  en: 'English',
  hi: 'हिंदी',
  mr: 'मराठी',
};

export const strings = {
  en: {
    appName: 'Aaspaas Pro',
    tagline: 'Help, around you. Now.',
    taglineSub: 'The smart switchboard for your neighbourhood.',
    aiSearch: 'AI Search',
    searchPlaceholder: 'Search for help (e.g., Mechanic, Ambulance, Key Maker)',
    findingMatch: 'Finding best match...',
    voiceNotSupported: 'Voice not supported on this browser. Try Chrome on Android.',
    voiceError: "Couldn't hear that. Try again.",
    myNeighbourhood: 'MY NEIGHBOURHOOD',
    online: 'Online',
    offline: 'Offline',
    activeOrders: (n: number) => `📋 You have ${n} active order${n === 1 ? '' : 's'} → View`,
    yourActiveOrders: '📋 Your active orders →',
    sendNewOrder: '📋 Send New Order',
    sendOrder: '📋 Send Order',
    yourActiveBookings: '📅 Your active bookings →',
    bookAgain: '📅 Book Again',
    bookService: '📅 Book a Service',
    connectAiBridge: 'Connect via AI-Bridge',
    cancel: 'Cancel',
    removeFromNeighbourhood: '🗑 Remove from My Neighbourhood',
    couldNotRemove: 'Could not remove',
    removedFromNeighbourhood: 'Removed from My Neighbourhood',
    aiBridge: 'AI-Bridge',
    briefingVendor: 'Briefing vendor via AI…',
    aiBriefUnavailable: 'AI brief unavailable — call directly',
    yourCallBrief: 'Your call brief',
    callNow: 'Call Now',
  },
  hi: {
    appName: 'आसपास प्रो',
    tagline: 'मदद, आपके आसपास। अभी।',
    taglineSub: 'आपके क्षेत्र का स्मार्ट सहायक।',
    aiSearch: 'AI खोज',
    searchPlaceholder: 'मदद खोजें (जैसे, मैकेनिक, एम्बुलेंस, चाबी वाला)',
    findingMatch: 'सबसे बेहतरीन विकल्प ढूंढ रहे हैं...',
    voiceNotSupported: 'इस ब्राउज़र में वॉइस सपोर्ट नहीं है। Android पर Chrome आज़माएं।',
    voiceError: 'सुनाई नहीं दिया। फिर कोशिश करें।',
    myNeighbourhood: 'मेरी सुरक्षित लिस्ट',
    online: 'ऑनलाइन',
    offline: 'ऑफलाइन',
    activeOrders: (n: number) => `📋 आपके ${n} सक्रिय ऑर्डर हैं → देखें`,
    yourActiveOrders: '📋 आपके सक्रिय ऑर्डर →',
    sendNewOrder: '📋 नया ऑर्डर भेजें',
    sendOrder: '📋 ऑर्डर भेजें',
    yourActiveBookings: '📅 आपकी सक्रिय बुकिंग →',
    bookAgain: '📅 फिर से बुक करें',
    bookService: '📅 सेवा बुक करें',
    connectAiBridge: 'AI-Bridge से जुड़ें',
    cancel: 'रद्द करें',
    removeFromNeighbourhood: '🗑 सुरक्षित लिस्ट से हटाएं',
    couldNotRemove: 'हटाया नहीं जा सका',
    removedFromNeighbourhood: 'सुरक्षित लिस्ट से हटाया गया',
    aiBridge: 'AI-Bridge',
    briefingVendor: 'AI द्वारा विक्रेता को जानकारी दी जा रही है…',
    aiBriefUnavailable: 'AI जानकारी उपलब्ध नहीं — सीधे कॉल करें',
    yourCallBrief: 'आपकी कॉल जानकारी',
    callNow: 'अभी कॉल करें',
  },
  mr: {
    appName: 'आसपास प्रो',
    tagline: 'मदत, तुमच्या आसपास. आत्ताच.',
    taglineSub: 'तुमच्या परिसराचा स्मार्ट सहाय्यक।',
    aiSearch: 'AI शोध',
    searchPlaceholder: 'मदत शोधा (उदा., मेकॅनिक, रुग्णवाहिका, किल्लीवाला)',
    findingMatch: 'उत्तम पर्याय शोधत आहोत...',
    voiceNotSupported: 'या ब्राउझरमध्ये व्हॉइस सपोर्ट नाही. Android वर Chrome वापरा.',
    voiceError: 'ऐकू आले नाही. पुन्हा प्रयत्न करा.',
    myNeighbourhood: 'माझी सेव्ह केलेली लिस्ट',
    online: 'ऑनलाइन',
    offline: 'ऑफलाइन',
    activeOrders: (n: number) => `📋 तुमचे ${n} ॲक्टिव्ह ऑर्डर्स आहेत → पहा`,
    yourActiveOrders: '📋 तुमचे सक्रिय ऑर्डर्स →',
    sendNewOrder: '📋 नवीन ऑर्डर पाठवा',
    sendOrder: '📋 ऑर्डर पाठवा',
    yourActiveBookings: '📅 तुमच्या ॲक्टिव्ह बुकिंग्ज →',
    bookAgain: '📅 पुन्हा बुक करा',
    bookService: '📅 सेवा बुक करा',
    connectAiBridge: 'AI-Bridge द्वारे कनेक्ट व्हा',
    cancel: 'रद्द करा',
    removeFromNeighbourhood: '🗑 सेव्ह केलेल्या लिस्टधून काढा',
    couldNotRemove: 'काढता आले नाही',
    removedFromNeighbourhood: 'सेव्ह केलेल्या लिस्टधून काढले गेले',
    aiBridge: 'AI-Bridge',
    briefingVendor: 'AI द्वारे विक्रेत्याला माहिती दिली जात आहे…',
    aiBriefUnavailable: 'AI माहिती उपलब्ध नाही — थेट कॉल करा',
    yourCallBrief: 'तुमची कॉल माहिती',
    callNow: 'आत्ताच कॉल करा',
  },
} as const;

export type StringKeys = keyof typeof strings.en;
