export type Language = 'en' | 'hi' | 'mr';

export const LANGUAGE_LABELS: Record<Language, string> = {
  en: 'English',
  hi: 'हिंदी',
  mr: 'मराठी',
};

export const strings = {
  en: {
    appName: 'Aaspaas Pro',
    tagline: 'Help, around you. Now.',
    taglineSub: 'The smart switchboard for your neighbourhood.',
    sos_title: 'SOS',
    sos_subtitle: 'TAP FOR HELP',
    aiSearch: 'AI Search',
    searchPlaceholder: 'Search for help (e.g., Mechanic, Ambulance, Key Maker)',
    findingMatch: 'Finding best match...',
    voiceNotSupported: 'Voice not supported on this browser. Try Chrome on Android.',
    voiceError: "Couldn't hear that. Try again.",
    myNeighbourhood: 'MY NEIGHBOURHOOD',
    online: 'Online',
    offline: 'Offline',
    nav_home: 'Home',
    nav_vendor: 'Vendor',
    nav_settings: 'Settings',
    category_mode_help: '🚨 Emergency & Help',
    category_mode_delivery: '🛒 Delivery',
    category_mode_appointment: '✂️ Book a Service',
    activeOrders: (n: number) => `📋 You have ${n} active order${n === 1 ? '' : 's'} → View`,
    yourActiveOrders: '📋 Your active orders →',
    sendNewOrder: '📋 Send New Order',
    sendOrder: '📋 Send Order',
    yourActiveBookings: '📅 Your active bookings →',
    bookAgain: '📅 Book Again',
    bookService: '📅 Book a Service',
    connectAiBridge: 'Connect via AI-Bridge',
    cancel: 'Cancel',
    removeFromNeighbourhood: '🗑 Remove from My Neighbourhood',
    couldNotRemove: 'Could not remove',
    removedFromNeighbourhood: 'Removed from My Neighbourhood',
    aiBridge: 'AI-Bridge',
    briefingVendor: 'Briefing vendor via AI…',
    aiBriefUnavailable: 'AI brief unavailable — call directly',
    yourCallBrief: 'Your call brief',
    callNow: 'Call Now',
    ai_bridge_call_limited: 'Call limited to X minutes',
    ai_bridge_connecting: 'Connecting your call... Please wait',
    ai_bridge_call_failed: 'Call failed. Please try again.',
    ai_bridge_call_now: '📞 Call Now',
    radar_connection_error: 'Connection Error',
    radar_all_emergencies: 'All emergencies',
    radar_back_home: 'Back to home',
    radar_expanding_scan: 'Expanding Scan',
    radar_scanning_area: 'Scanning Area',
    radar_finding_nearby: 'Finding nearby ',
    radar_searching_within: 'Searching within ',
    radar_km: ' km',
    radar_live: 'Live Radar',
    radar_match: 'match',
    radar_matches: 'matches',
    radar_found: ' found',
    radar_showing_within: 'Showing nearest help within ',
    radar_no_helpers_15: 'No helpers found within 15km',
    radar_no_helpers_area: 'No helpers found in your area yet. Aaspaas Pro is growing — check back soon or try a different category.',
    radar_expand_25: 'Expand to 25km',
    radar_expand_50: 'Expand to 50km',
    radar_no_private: 'No private responders currently online',
    radar_official_services: 'You can still reach official emergency services below.',
    radar_helped: 'Helped ',
    radar_person: 'person',
    radar_people: 'people',
    radar_orders_served: ' orders served',
    radar_on_time: '% on time',
    radar_location_unknown: 'Location unknown',
    radar_est_arrival: 'Est. arrival ~',
    radar_min: ' min',
    radar_verification_progress: 'Verification in Progress — Proceed with caution.',
    radar_not_verified: 'Warning: Identity Not Verified — connect at your own risk.',
    radar_connect_ai: 'Connect via AI-Bridge',
    radar_your_brief: 'Your call brief',
    radar_cancel: 'Cancel',
    radar_booking_requested: 'Booking Requested',
    radar_order_sent: 'Order Sent',
    radar_book_again: 'Book Again',
    radar_send_new_order: 'Send New Order',
    radar_book_service: 'Book a Service',
    radar_send_order: 'Send Order',
    radar_marked: 'Marked!',
    radar_delivered_on_time: 'Delivered on Time',
    radar_he_helped: 'He Helped Me',
    radar_save_as: 'Save as My ',
    radar_vendor_fallback: 'Vendor',
    radar_saved_success: 'Saved! Find them on your home screen.',
    radar_could_not_save: 'Could not save',
    radar_thank_community: 'Thank you! This helps the community.',
    radar_signal_unknown: 'Signal: Unknown',
    radar_signal_strong: 'Signal: Strong',
    radar_last_active: 'Last Active: ',
    radar_mins_ago: ' mins ago',
    radar_h_ago: 'h ago',
    radar_d_ago: 'd ago',
    radar_govt_help: 'Govt. Help',
    radar_tap_to_open: 'Tap to open · Primary line: ',
    radar_local_police: 'Local Police',
    radar_police_tagline: 'Nearest police station dispatch',
    vendor_verified_title: 'You are Verified!',
    vendor_verified_body: 'Your Green badge is live. Customers trust you more.',
    vendor_verified_cta: 'Tap the power button to go Online.',
    vendor_submitted_title: 'Verification Submitted',
    vendor_submitted_body:
      'Our team will review your details within 24 hours. Meanwhile — tap the power button to go Online!',
    vendor_geo_not_supported: 'Geolocation not supported on this device.',
    vendor_location_captured: 'Shop location captured',
    vendor_location_failed: "Couldn't get location",
    vendor_name_invalid: "That name doesn't look right",
    vendor_name_invalid_body: 'Please enter your real name (letters only, no random keys).',
    vendor_shopname_invalid: 'Shop name looks invalid',
    vendor_shopname_invalid_body: 'Please enter a real shop name we can show to customers.',
    vendor_specify_service: 'Specify your service',
    vendor_specify_service_body: "When choosing 'Other', describe your service in plain words.",
    vendor_choose_service: 'Choose how you serve customers',
    vendor_choose_service_body: 'Pick either visit & help or deliver & supply.',
    vendor_phone_invalid: 'Invalid phone number',
    vendor_phone_invalid_body: 'Enter a valid 10-digit Indian mobile number.',
    vendor_upi_invalid: 'Invalid UPI ID',
    vendor_upi_invalid_body: 'UPI must look like handle@bank (e.g. ramesh@okicici).',
    vendor_welcome_title: 'Welcome aboard!',
    vendor_welcome_body: 'Identity linked. Capture a live shop photo to upgrade to Verified.',
    vendor_welcome_back: 'Welcome back!',
    vendor_not_found: 'No vendor found with this number. Please register first.',
    vendor_location_required: 'Location required to go live',
    vendor_location_required_body: 'Mobile services need a fresh GPS fix when going online.',
    vendor_status_failed: "Couldn't update status",
    vendor_you_are_live: "You're live ✨",
    vendor_you_are_offline: "You're offline",
    vendor_live_body: 'Live position updated. Customers nearby can now find you.',
    vendor_live_body_short: 'Customers nearby can now find you.',
    vendor_offline_body: "You won't receive new requests.",
    vendor_upi_format_invalid: 'Invalid UPI format',
    vendor_upi_format_body: 'Expected handle@bank',
    vendor_upi_check_failed: "Couldn't verify UPI",
    vendor_upi_verified: 'UPI verified · ',
    vendor_upi_bank_valid: 'Bank handle looks valid.',
    vendor_set_location_first: 'Set your shop location first',
    vendor_set_location_first_body: "Tap 'Update Shop Location' before capturing the photo.",
    vendor_upload_failed: 'Upload failed',
    vendor_save_verification_failed: "Couldn't save verification",
    vendor_photo_verified: 'Shop photo verified',
    vendor_green_badge_live: 'Green badge live.',
    vendor_awaiting_admin: 'Awaiting final admin approval for the Green badge.',
    vendor_location_reset_confirm:
      'Changing your location will require re-verification of your shop. Continue?',
    vendor_location_update_failed: "Couldn't update location",
    vendor_reverification_required: 'Re-verification required',
    vendor_reverification_body: 'Capture a new live shop photo to regain Verified status.',
    vendor_location_updated: 'Location updated',
    vendor_location_updated_body: 'Your shop coordinates have been saved.',
    vendor_note_save_failed: 'Could not save note',
    vendor_note_saved: 'Note saved!',
    vendor_back_home: 'Back to home',
    vendor_mode_title: 'Vendor Mode',
    vendor_tagline: 'Earn from your skills.',
    vendor_trialDaysLeft: (days: number) =>
      `🎁 Free trial: ${days} day${days === 1 ? '' : 's'} left`,
    vendor_trialExpired:
      '⚠️ Your free trial has ended. Subscribe to stay active.',
    landing_emergencyTitle: 'Emergency Help',
    landing_emergencyDesc: 'Find mechanics, ambulance, plumbers instantly',
    landing_deliveryTitle: 'Local Delivery',
    landing_deliveryDesc: 'Order from nearby kirana, pharmacy',
    landing_bookingTitle: 'Book Services',
    landing_bookingDesc: 'Beautician, tailor, cook at your doorstep',
    landing_downloadApp: 'Download the App',
    landing_vendorRegister: 'For vendors: Register your shop and get customers',
    landing_copyright: '© 2026 Aaspaas Pro',
    vendor_view_orders: 'View incoming orders',
    vendor_your_name: 'Your Name',
    vendor_name_placeholder: 'Ramesh Kumar',
    vendor_shop_name: 'Shop Name',
    vendor_shop_placeholder: 'Ramesh Tyre Works',
    vendor_category_label: 'Category',
    vendor_specify_category: 'Specify Your Service',
    vendor_specify_placeholder: 'e.g. Carpenter, Tailor, Tiffin Service',
    vendor_specify_hint: 'Please describe your service in plain words.',
    vendor_understanding: 'Understanding your service...',
    vendor_more_specific: 'Please choose a more specific category.',
    vendor_we_think: 'We think you mean:',
    vendor_help_service: 'Help service',
    vendor_delivery_service: 'Delivery service',
    vendor_govt_service: '· Government service',
    vendor_confirm: 'Confirm',
    vendor_confirmed_category: 'Confirmed category:',
    vendor_how_serve: 'How do you serve your customers?',
    vendor_mode_visit: '🤝 I visit & help',
    vendor_mode_visit_eg: 'Mechanic, Plumber etc',
    vendor_mode_deliver: '📦 I deliver & supply',
    vendor_mode_deliver_eg: 'Kirana, Pharmacy etc',
    vendor_mode_booking: '📅 I take bookings',
    vendor_mode_booking_eg: 'Beautician, Tailor etc',
    vendor_phone_label: 'Phone (required)',
    vendor_phone_placeholder: '+91 98xxxxxxxx',
    vendor_phone_hint: 'Enter a valid 10-digit Indian mobile number.',
    vendor_upi_label: 'UPI ID',
    vendor_upi_placeholder: 'name@okbank',
    vendor_upi_hint: 'UPI must look like handle@bank.',
    vendor_note_label: 'Note for customers (optional)',
    vendor_referralCodeLabel: 'Referral Code (optional)',
    vendor_referralCodePlaceholder: 'e.g. MAT-9973',
    vendor_note_placeholder:
      'e.g. Delivery every evening 6–8pm. Home visits on weekdays only.',
    vendor_gps_warning:
      'Please capture your location from your shop, not from home. This helps customers find you accurately.',
    vendor_capture_location: '📍 Capture Shop Location',
    vendor_register_btn: 'Register me',
    vendor_register_hint: 'Registration unlocks once a valid phone number is entered.',
    vendor_or: 'or',
    vendor_already_registered: 'Already registered? Find my account',
    vendor_find_account_title: 'Find your vendor account',
    vendor_find_account_hint: 'Enter the phone number you registered with',
    vendor_find_btn: 'Find My Account',
    vendor_back_to_reg: '← Back to registration',
    vendor_ready: 'Ready to Help',
    vendor_offline_label: 'Offline',
    vendor_tap_offline: 'Tap to go offline',
    vendor_offline_active_orders_title: 'You have active orders for today',
    vendor_offline_active_orders_message:
      'Please contact your customers and inform them before going offline.',
    vendor_stay_online: 'Stay Online',
    vendor_go_offline_anyway: 'Go Offline Anyway',
    vendor_tap_online: 'Tap to Go Online',
    vendor_customers_waiting: 'Customers nearby are waiting!',
    vendor_mobile_gps: 'Mobile service · GPS refreshes each time you go live.',
    vendor_verified_pro: 'Verified Professional',
    vendor_referEarn: '🎁 Refer & Earn',
    vendor_referCopyLink: '📋 Copy Link',
    vendor_referShare: '📤 Share',
    vendor_referLinkCopied: 'Link copied!',
    vendor_referVendorCredit: (amount: number) =>
      `Refer a vendor → earn ₹${amount} credit over 3 months`,
    vendor_referUserCredit: (amount: number) => `Refer a user → earn ₹${amount} credit`,
    liveTracking_callWithCare: 'call with care',
    vendor_pending_label: 'Verification Pending',
    vendor_complete_verification: 'Complete your verification',
    vendor_verification_shop: 'Verification & shop',
    vendor_close: '✕ Close',
    vendor_verification_heading: 'Verification',
    vendor_phone_on_file: 'Phone on file',
    vendor_not_provided: 'Not provided',
    vendor_upi_bank_match: 'UPI bank-match',
    vendor_checking: 'Checking…',
    vendor_verify_upi_btn: 'Verify UPI',
    vendor_photo_gps: 'Live shop photo + GPS match',
    vendor_photo_captured: 'Captured & GPS verified',
    vendor_photo_hint: 'Live camera only · within 75 m of shop',
    vendor_reshoot: 'Re-shoot',
    vendor_capture: 'Capture',
    vendor_captured_shop: 'Captured shop',
    vendor_badge_approval:
      'The Green "Business Verified" badge glows only after admin approval',
    vendor_approved: '✅ approved',
    vendor_approval_pending: 'pending',
    vendor_update_location: 'Update Shop Location',
    vendor_location_reset_warning: 'Moving location will reset your Verified status.',
    vendor_note_customers: 'Note for customers',
    vendor_note_edit_placeholder: 'e.g. Delivery every evening 6–8pm',
    vendor_saving: 'Saving…',
    vendor_save_note: 'Save Note',
    vendor_location_set: 'Location set',
    vendor_mismatch_title: 'Location mismatch',
    myOrders_statusSent: '📤 Sent',
    myOrders_statusSeen: '👀 Vendor saw your order',
    myOrders_statusNoResponse: '⚠️ No response yet',
    myOrders_statusFulfilled: '✅ Vendor fulfilled your order',
    myOrders_errCouldNotUpdate: 'Could not update',
    myOrders_errCouldNotCancel: 'Could not cancel',
    myOrders_bookingCancelled: 'Booking cancelled.',
    myOrders_shopFallback: 'Shop',
    myOrders_backToHome: 'Back to home',
    myOrders_appName: 'Aaspaas Pro',
    myOrders_heading: 'My orders',
    myOrders_noOrders: 'No active orders.',
    myOrders_noOrdersHint: 'Search for a vendor to send your first order!',
    myOrders_findVendors: 'Find Vendors →',
    myOrders_deliverySlotPrefix: '🕐 ',
    myOrders_locationComeToYou: "🏠 They'll come to you",
    myOrders_locationVisitShop: "🏪 You'll visit their shop",
    myOrders_locationTbd: '📞 Location TBD',
    myOrders_apptAround: '📅 Around ',
    myOrders_apptConfirmed: '· ✅ Vendor confirmed',
    myOrders_apptDeclined: '· ❌ Vendor declined',
    myOrders_apptCancelled: '· ❌ Vendor cancelled',
    myOrders_apptAwaiting: '· ⏳ Awaiting confirmation',
    myOrders_dismiss: '🗑 Dismiss',
    myOrders_cancelBooking: 'Cancel Booking',
    myOrders_sameDayWarning: '⚠️ Same-day changes require a call to the vendor first',
    myOrders_callThenCancel: '📞 Connect via AI-Bridge to Cancel',
    myOrders_callDone: '✅ Call done — you may now cancel your booking',
    myOrders_confirmCancelQ: 'Are you sure you want to cancel?',
    myOrders_yesCancel: 'Yes, Cancel',
    myOrders_keepIt: 'Keep it',
    myOrders_saving: 'Saving…',
    myOrders_delivered: '✅ Delivered! Tap to dismiss',
    myOrders_cancelOrder: 'Cancel Order',
    myOrders_confirmCancelOrderQ: 'Are you sure you want to cancel this order?',
    myOrders_cannotCancel: '🔒 Cannot cancel — vendor is already on it',
    myOrders_cancelledByVendor: 'Cancelled by vendor',
    myOrders_vendorCancelledDefault: 'Vendor cancelled this order',
    vendor_stopped_warning:
      'Your helper seems to have stopped. Are they okay? Try calling them.',
    vendor_distance: 'Vendor is away',
    vendor_last_updated: 'Updated',
    user_vendor_offline_title: 'Your vendor has gone offline',
    user_vendor_offline_body:
      'Your order may be affected. Please find another vendor if needed.',
    settings_vendorVerified: 'Vendor verified ✅',
    settings_removeVerifyConfirm: 'Remove verification from this vendor?',
    settings_verificationRemoved: 'Verification removed',
    settings_devMenuUnlocked: 'Developer menu unlocked',
    settings_clearDataTitle: 'Clear All My Data?',
    settings_clearDataDescription:
      'This will remove your phone number, saved addresses, order history, language and theme preferences, and vendor session from this device. This cannot be undone.',
    settings_clearDataConfirm: 'Clear Everything',
    settings_localDataCleared: 'Local data cleared',
    settings_heading: 'Settings',
    settings_tagline: 'Make it yours.',
    settings_switchRole: 'Switch role',
    settings_switchRoleHintPrefix: 'Use the bottom navigation — ',
    settings_switchRoleHome: 'Home',
    settings_switchRoleForHelp: ' for help,',
    settings_switchRoleVendor: 'Vendor',
    settings_switchRoleToEarn: ' to earn.',
    settings_myIdentity: 'My Identity',
    settings_phonePrefix: '📞 ',
    settings_registered: 'Registered — orders sync across devices',
    settings_noPhone: 'No phone registered yet',
    settings_noPhoneHint: 'Save a vendor or send an order to register',
    settings_devicePrefix: 'Device: ',
    settings_deviceEllipsis: '…',
    settings_myDeliveryAddresses: '📍 My Delivery Addresses',
    settings_noAddresses: 'No saved addresses yet.',
    settings_shareApp: '📤 Share App',
    settings_inviteFriend: 'Invite a Friend',
    settings_language: 'Language',
    settings_accessibility: '♿ Accessibility',
    settings_largeText: 'Large Text',
    settings_largeTextHint: 'Increases text size across the app',
    cancelReasons: 'Cancel Reasons',
    cancelReasonsSubtitle: 'Shown to users when you cancel an order',
    saveReasons: 'Save Reasons',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    settings_notifications: 'Notifications',
    settings_vibrate: 'Vibrate on new order',
    settings_sound: 'Sound on new order',
    settings_sound_body: 'Manage notification sound in Android Settings',
    onboard_notifications_title: 'Get orders instantly',
    onboard_notifications_body:
      'Allow notifications so you never miss an incoming order.',
    onboard_allow_notifications: 'Allow Notifications',
    onboard_skip: 'Skip for now',
    onboard_location_title: 'Share your location',
    onboard_location_body:
      'Customers need to find you. Allow location access for accurate radar results.',
    onboard_allow_location: 'Allow Location',
    onboard_battery_title: 'Never miss an order',
    onboard_battery_body:
      'Disable battery optimization so Aaspaas Pro runs reliably in background.',
    onboard_open_settings: 'Open Settings',
    onboard_battery_skip: "I'll do this later",
    onboard_camera_title: 'Verify your shop',
    onboard_camera_body:
      'A shop photo earns you a trust badge. Customers prefer verified vendors.',
    onboard_allow_camera: 'Allow Camera',
    onboard_done_title: "You're all set!",
    onboard_done_body: 'Start accepting orders and grow your business.',
    onboard_get_started: 'Get Started',
    settings_myShop: 'My Shop',
    settings_dotSeparator: ' · ',
    settings_vendorNotePrefix: '📌 ',
    settings_loading: 'Loading...',
    settings_myAnalytics: 'My Analytics',
    settings_totalOrders: 'Total Orders',
    settings_thisMonth: 'This Month',
    settings_fulfilled: 'Fulfilled',
    settings_declined: 'Declined',
    settings_adminHealth: 'Admin — App Health',
    settings_adminOnly: 'Only visible to you.',
    settings_orders: 'Orders',
    settings_allTime: 'All Time',
    settings_thisWeek: 'This Week',
    settings_today: 'Today',
    settings_vendors: 'Vendors',
    settings_total: 'Total',
    settings_activeToday: 'Active Today',
    settings_newThisWeek: 'New This Week',
    settings_unverified: 'Unverified',
    admin_pendingCategories: '🗂️ Pending Categories',
    admin_approve: 'Approve',
    admin_reject: 'Reject',
    admin_noPendingCategories: 'No pending categories',
    settings_vendorVerification: 'Vendor Verification',
    settings_unverifiedFirst: 'Unverified vendors shown first.',
    settings_searchPlaceholder: 'Search by name, shop, phone...',
    settings_noVendorsFound: 'No vendors found.',
    settings_live: 'LIVE',
    settings_btnLoading: '...',
    settings_verified: 'Verified',
    settings_trustSecurity: 'Trust & Security',
    settings_dbConnected: 'Database: Connected & Secure',
    settings_tlsNote: 'All data is transmitted over TLS and protected with row-level security.',
    settings_appName: 'Aaspaas Pro',
    settings_appTagline: 'Help, around you. Now.',
    settings_version: 'Version 1.0.0 · Built for Bharat',
    settings_copyright: '© 2026 Aaspaas Pro',
    settings_devMenu: 'Developer menu',
    settings_hideDevMenu: 'Hide developer menu',
    settings_clearMyData: 'Clear My Data',
    settings_verifyVendor: 'Verify Vendor',
    settings_check1: 'Called vendor on registered phone — person picked up',
    settings_check2: 'Name matches what they said on call',
    settings_check3: 'Vendor is aware they registered on Aaspaas',
    settings_check4: 'Shop physically exists at registered location',
    settings_check5: 'Shop name matches signboard / what they said',
    settings_check6: 'Category matches actual service they provide',
    settings_check7: 'Service mode is correct (help / delivery / appointment)',
    settings_check8: 'No duplicate account found (same phone or same shop)',
    settings_check9: 'Shop photo uploaded and looks genuine',
    settings_check10: 'UPI ID verified (if provided)',
    settings_check11: 'No suspicious activity (multiple rapid orders, fake numbers)',
    settings_check12: 'Vendor understands Aaspaas usage rules',
    settings_verifying: 'Verifying...',
    settings_markVerified: '✅ Mark as Verified',
    settings_cancel: 'Cancel',
    parchi_slotAsap: 'As soon as possible',
    parchi_slotMorning: 'Morning (before 12pm)',
    parchi_slotAfternoon: 'Afternoon (12–4pm)',
    parchi_slotEvening: 'Evening (after 4pm)',
    parchi_slotTomorrow: 'Tomorrow',
    parchi_errNoOrder: 'Please type your order.',
    parchi_errNoAddress: 'Please add a delivery address.',
    parchi_errNoDateTime: 'Please select appointment date and time.',
    parchi_locationComeToMe: ' [Come to my place]',
    parchi_locationVisitShop: " [I'll visit your shop]",
    parchi_locationTbd: ' [Location TBD]',
    parchi_errCouldNotSend: 'Could not send order',
    parchi_toastBookingSuccess: '📅 Booking requested!',
    parchi_toastOrderSuccess: '✅ Order sent! They will see it shortly.',
    parchi_slotAsapEmoji: '🚀 As soon as possible',
    parchi_slotMorningEmoji: '🌅 Morning (before 12pm)',
    parchi_slotAfternoonEmoji: '🌞 Afternoon (12–4pm)',
    parchi_slotEveningEmoji: '🌆 Evening (after 4pm)',
    parchi_slotTomorrowEmoji: '📅 Tomorrow',
    parchi_titleBook: 'Book with ',
    parchi_titleOrder: 'Order to ',
    parchi_onlineBooking: '🟢 Online — will confirm your booking shortly',
    parchi_offlineBooking: '⚫ Offline — will confirm when they return',
    parchi_onlineOrder: '🟢 Online — will see this shortly',
    parchi_offlineOrder: '⚫ Offline — will see when they return',
    parchi_vendorNotePrefix: '📌 ',
    parchi_deliveryAddress: 'Delivery Address',
    parchi_loadingAddresses: 'Loading addresses...',
    parchi_useDifferentAddress: '+ Use a different address',
    parchi_addressPlaceholder: 'e.g. Flat 4B, Green Park, Near Water Tank',
    parchi_saveAddress: 'Save this address for next time',
    parchi_whereQuestion: '📍 Where?',
    parchi_locationComeToMeBtn: '🏠 Come to me',
    parchi_locationVisitBtn: "🏪 I'll visit",
    parchi_locationDecideLater: '📞 Decide later',
    parchi_whenAppt: '📅 When do you need them?',
    parchi_dateLabel: 'Date',
    parchi_timeLabel: 'Time',
    parchi_whenDelivery: '🕐 When do you need it?',
    parchi_orderLabel: 'Your order',
    parchi_placeholderAppt: 'Any special notes?\ne.g. Full facial, 2 people, ground floor',
    parchi_placeholderOrder: 'Type your order...\ne.g. 1kg atta, 2 soaps, Colgate toothpaste',
    parchi_charSeparator: ' / ',
    parchi_cancellationAppt:
      'ℹ️ Free cancellation before your booking day. Same-day changes need a quick call first.',
    parchi_cancellationOrder:
      "ℹ️ You can cancel this order only if the vendor hasn't seen it yet.",
    parchi_btnConfirmBooking: '📅 Confirm Booking',
    parchi_btnSendOrder: '📋 Send Order',
    parchi_btnCancel: 'Cancel',
    incoming_errCouldNotUpdate: 'Could not update order',
    incoming_errCouldNotUpdateAppt: 'Could not update appointment',
    incoming_apptConfirmed: '✅ Appointment confirmed!',
    incoming_apptDeclined: 'Appointment declined.',
    incoming_errCouldNotCancel: 'Could not cancel',
    incoming_bookingCancelled: 'Booking cancelled.',
    incoming_statusNew: 'New',
    incoming_statusSeen: 'Seen',
    incoming_statusDone: 'Done ✅',
    incoming_heading: '📋 Incoming Orders',
    incoming_unreadCap: '99+',
    incoming_empty: 'No orders yet!',
    incoming_addressPrefix: '📍 ',
    incoming_slotPrefix: '🕐 ',
    incoming_locationComeToYou: '🏠 Coming to you',
    incoming_locationVisitShop: '🏪 Will visit your shop',
    incoming_locationTbd: '📞 Location TBD',
    incoming_apptAround: '📅 Around ',
    incoming_btnConfirm: '✅ Confirm',
    incoming_btnDecline: '❌ Decline',
    incoming_bannerConfirmed: '✅ Appointment Confirmed',
    incoming_bannerDeclined: '❌ Appointment Declined',
    incoming_cancelAppt: 'Cancel Appointment',
    incoming_sameDayWarning: '⚠️ Same-day cancellation — call customer first',
    incoming_callThenCancel: '📞 Connect via AI-Bridge to Cancel',
    incoming_callDone: '✅ Call done — you may now cancel',
    incoming_callBridge: '📞 Connect via AI-Bridge',
    incoming_saving: 'Saving…',
    incoming_markDone: '✅ Mark Done',
    incoming_btnAccept: '✅ Accept',
    status_accepted: 'Vendor accepted — on the way',
    order_already_taken: 'This order was already accepted by another vendor',
    cancelOrder: 'Cancel Order',
    cancelReason: 'Why are you cancelling?',
    confirmCancel: 'Confirm Cancel',
    orderCancelled: 'Order cancelled',
    other: 'Other',
    cancelReasonPlaceholder: 'Type reason...',
    editOrder: 'Edit Order',
    saveChanges: 'Save Changes',
    orderUpdated: 'Order updated',
    vendorSeenWarning:
      'Vendor has seen this order. They will be notified of your changes.',
    rating_errCouldNotSave: 'Could not save rating',
    rating_errCouldNotSaveFeedback: 'Could not save feedback',
    rating_heading: 'How was your order?',
    rating_btnDelivered: '📦 Delivered on Time',
    rating_btnHelped: '✅ He Helped Me',
    rating_btnIssue: '⚠️ Had an issue',
    rating_helperText: 'Please share your feedback to dismiss',
  },
  hi: {
    appName: 'आसपास प्रो',
    tagline: 'मदद, आपके आसपास। अभी।',
    taglineSub: 'आपके क्षेत्र का स्मार्ट सहायक।',
    sos_title: 'SOS',
    sos_subtitle: 'मदद के लिए दबाएं',
    aiSearch: 'AI खोज',
    searchPlaceholder: 'मदद खोजें (जैसे, मैकेनिक, एम्बुलेंस, चाबी वाला)',
    findingMatch: 'सबसे बेहतरीन विकल्प ढूंढ रहे हैं...',
    voiceNotSupported: 'इस ब्राउज़र में वॉइस सपोर्ट नहीं है। Android पर Chrome आज़माएं।',
    voiceError: 'सुनाई नहीं दिया। फिर कोशिश करें।',
    myNeighbourhood: 'मेरी सुरक्षित लिस्ट',
    online: 'ऑनलाइन',
    offline: 'ऑफलाइन',
    nav_home: 'होम',
    nav_vendor: 'विक्रेता',
    nav_settings: 'सेटिंग्स',
    category_mode_help: '🚨 आपातकाल और मदद',
    category_mode_delivery: '🛒 डिलीवरी',
    category_mode_appointment: '✂️ सेवा बुक करें',
    activeOrders: (n: number) => `📋 आपके ${n} सक्रिय ऑर्डर हैं → देखें`,
    yourActiveOrders: '📋 आपके सक्रिय ऑर्डर →',
    sendNewOrder: '📋 नया ऑर्डर भेजें',
    sendOrder: '📋 ऑर्डर भेजें',
    yourActiveBookings: '📅 आपकी सक्रिय बुकिंग →',
    bookAgain: '📅 फिर से बुक करें',
    bookService: '📅 सेवा बुक करें',
    connectAiBridge: 'AI-Bridge से जुड़ें',
    cancel: 'रद्द करें',
    removeFromNeighbourhood: '🗑 सुरक्षित लिस्ट से हटाएं',
    couldNotRemove: 'हटाया नहीं जा सका',
    removedFromNeighbourhood: 'सुरक्षित लिस्ट से हटाया गया',
    aiBridge: 'AI-Bridge',
    briefingVendor: 'AI द्वारा विक्रेता को जानकारी दी जा रही है…',
    aiBriefUnavailable: 'AI जानकारी उपलब्ध नहीं — सीधे कॉल करें',
    yourCallBrief: 'आपकी कॉल जानकारी',
    callNow: 'अभी कॉल करें',
    ai_bridge_call_limited: 'कॉल X मिनट तक सीमित',
    ai_bridge_connecting: 'आपकी कॉल कनेक्ट हो रही है... कृपया प्रतीक्षा करें',
    ai_bridge_call_failed: 'कॉल विफल। कृपया पुनः प्रयास करें।',
    ai_bridge_call_now: '📞 अभी कॉल करें',
    radar_connection_error: 'कनेक्शन त्रुटी',
    radar_all_emergencies: 'सभी आपातकाल',
    radar_back_home: 'होम पर जाएं',
    radar_expanding_scan: 'खोज बढ़ा रहे हैं',
    radar_scanning_area: 'क्षेत्र स्कैन हो रहा है',
    radar_finding_nearby: 'नजदीकी खोज रहे हैं ',
    radar_searching_within: 'खोज हो रही है ',
    radar_km: ' किमी',
    radar_live: 'लाइव रडार',
    radar_match: 'परिणाम',
    radar_matches: 'परिणाम',
    radar_found: ' मिले',
    radar_showing_within: 'नजदीकी सहायता दिख रही है ',
    radar_no_helpers_15: '15 किमी में कोई सहायक नहीं मिला',
    radar_no_helpers_area: 'आपके क्षेत्र में अभी कोई सहायक नहीं है। Aaspaas Pro बढ़ रहा है — जल्द वापस आएं या दूसरी श्रेणी आजमाएं।',
    radar_expand_25: '25 किमी तक बढ़ाएं',
    radar_expand_50: '50 किमी तक बढ़ाएं',
    radar_no_private: 'अभी कोई निजी सहायक ऑनलाइन नहीं है',
    radar_official_services: 'आप नीचे सरकारी आपातकालीन सेवाओं तक पहुंच सकते हैं।',
    radar_helped: 'मदद की ',
    radar_person: 'व्यक्ति',
    radar_people: 'लोग',
    radar_orders_served: ' ऑर्डर पूरे किए',
    radar_on_time: '% समय पर',
    radar_location_unknown: 'स्थान अज्ञात',
    radar_est_arrival: 'अनुमानित आगमन ~',
    radar_min: ' मिनट',
    radar_verification_progress: 'सत्यापन जारी है — सावधानी से आगे बढ़ें।',
    radar_not_verified: 'चेतावनी: पहचान सत्यापित नहीं — अपने जोखिम पर जुड़ें।',
    radar_connect_ai: 'AI-Bridge से जुड़ें',
    radar_your_brief: 'आपका कॉल सारांश',
    radar_cancel: 'रद्द करें',
    radar_booking_requested: 'बुकिंग अनुरोध भेजा',
    radar_order_sent: 'ऑर्डर भेजा गया',
    radar_book_again: 'फिर बुक करें',
    radar_send_new_order: 'नया ऑर्डर भेजें',
    radar_book_service: 'सेवा बुक करें',
    radar_send_order: 'ऑर्डर भेजें',
    radar_marked: 'चिह्नित!',
    radar_delivered_on_time: 'समय पर डिलीवर हुआ',
    radar_he_helped: 'इन्होंने मेरी मदद की',
    radar_save_as: 'मेरे ',
    radar_vendor_fallback: 'विक्रेता',
    radar_saved_success: 'सहेजा गया! होम स्क्रीन पर देखें।',
    radar_could_not_save: 'सहेज नहीं सका',
    radar_thank_community: 'धन्यवाद! यह समुदाय की मदद करता है।',
    radar_signal_unknown: 'सिग्नल: अज्ञात',
    radar_signal_strong: 'सिग्नल: मजबूत',
    radar_last_active: 'अंतिम सक्रिय: ',
    radar_mins_ago: ' मिनट पहले',
    radar_h_ago: 'घंटे पहले',
    radar_d_ago: 'दिन पहले',
    radar_govt_help: 'सरकारी मदद',
    radar_tap_to_open: 'खोलने के लिए टैप करें · मुख्य लाइन: ',
    radar_local_police: 'स्थानीय पुलिस',
    radar_police_tagline: 'नजदीकी पुलिस स्टेशन',
    vendor_verified_title: 'आप वेरिफाइड हैं!',
    vendor_verified_body: 'आपका हरा बैज लाइव है। ग्राहक आप पर अधिक भरोसा करते हैं।',
    vendor_verified_cta: 'ऑनलाइन होने के लिए पावर बटन दबाएं।',
    vendor_submitted_title: 'वेरिफिकेशन जमा हुआ',
    vendor_submitted_body:
      'हमारी टीम 24 घंटों में आपकी जानकारी जांचेगी। इस बीच — ऑनलाइन होने के लिए पावर बटन दबाएं!',
    vendor_geo_not_supported: 'इस डिवाइस पर जियोलोकेशन उपलब्ध नहीं है।',
    vendor_location_captured: 'दुकान का स्थान मिला',
    vendor_location_failed: 'स्थान नहीं मिला',
    vendor_name_invalid: 'यह नाम सही नहीं लगता',
    vendor_name_invalid_body: 'कृपया अपना असली नाम दर्ज करें (केवल अक्षर)।',
    vendor_shopname_invalid: 'दुकान का नाम सही नहीं लगता',
    vendor_shopname_invalid_body: 'कृपया एक असली दुकान का नाम दर्ज करें।',
    vendor_specify_service: 'अपनी सेवा बताएं',
    vendor_specify_service_body: "'अन्य' चुनते समय, अपनी सेवा सरल शब्दों में बताएं।",
    vendor_choose_service: 'ग्राहकों की सेवा कैसे करते हैं?',
    vendor_choose_service_body: 'विज़िट और मदद या डिलीवरी में से चुनें।',
    vendor_phone_invalid: 'गलत फ़ोन नंबर',
    vendor_phone_invalid_body: '10 अंकों का सही मोबाइल नंबर डालें।',
    vendor_upi_invalid: 'गलत UPI ID',
    vendor_upi_invalid_body: 'UPI ऐसा होना चाहिए: ramesh@okicici',
    vendor_welcome_title: 'स्वागत है!',
    vendor_welcome_body: 'पहचान जुड़ी। वेरिफाइड होने के लिए दुकान की फोटो लें।',
    vendor_welcome_back: 'वापस स्वागत है!',
    vendor_not_found: 'इस नंबर से कोई दुकानदार नहीं मिला। पहले रजिस्टर करें।',
    vendor_location_required: 'लाइव होने के लिए लोकेशन जरूरी है',
    vendor_location_required_body: 'ऑनलाइन होने पर नया GPS लोकेशन चाहिए।',
    vendor_status_failed: 'स्टेटस अपडेट नहीं हुआ',
    vendor_you_are_live: 'आप लाइव हैं ✨',
    vendor_you_are_offline: 'आप ऑफलाइन हैं',
    vendor_live_body: 'लाइव लोकेशन अपडेट हुआ। पास के ग्राहक आपको ढूंढ सकते हैं।',
    vendor_live_body_short: 'पास के ग्राहक आपको ढूंढ सकते हैं।',
    vendor_offline_body: 'नए ऑर्डर नहीं मिलेंगे।',
    vendor_upi_format_invalid: 'गलत UPI फॉर्मेट',
    vendor_upi_format_body: 'handle@bank होना चाहिए',
    vendor_upi_check_failed: 'UPI चेक नहीं हो सका',
    vendor_upi_verified: 'UPI वेरिफाइड · ',
    vendor_upi_bank_valid: 'बैंक हैंडल सही लगता है।',
    vendor_set_location_first: 'पहले दुकान की लोकेशन सेट करें',
    vendor_set_location_first_body: "फोटो लेने से पहले 'दुकान लोकेशन अपडेट करें' दबाएं।",
    vendor_upload_failed: 'अपलोड नहीं हुआ',
    vendor_save_verification_failed: 'वेरिफिकेशन सेव नहीं हुआ',
    vendor_photo_verified: 'दुकान फोटो वेरिफाइड',
    vendor_green_badge_live: 'हरा बैज लाइव है।',
    vendor_awaiting_admin: 'हरे बैज के लिए एडमिन की मंजूरी बाकी है।',
    vendor_location_reset_confirm:
      'लोकेशन बदलने पर दुकान की दोबारा वेरिफिकेशन होगी। जारी रखें?',
    vendor_location_update_failed: 'लोकेशन अपडेट नहीं हुआ',
    vendor_reverification_required: 'दोबारा वेरिफिकेशन जरूरी है',
    vendor_reverification_body: 'वेरिफाइड स्टेटस पाने के लिए नई दुकान फोटो लें।',
    vendor_location_updated: 'लोकेशन अपडेट हुआ',
    vendor_location_updated_body: 'आपकी दुकान की लोकेशन सेव हो गई।',
    vendor_note_save_failed: 'नोट सेव नहीं हुआ',
    vendor_note_saved: 'नोट सेव हो गया!',
    vendor_back_home: 'होम पर जाएं',
    vendor_mode_title: 'दुकानदार मोड',
    vendor_tagline: 'अपनी कला से कमाएं।',
    vendor_trialDaysLeft: (days: number) => `🎁 निःशुल्क ट्रायल: ${days} दिन बाकी`,
    vendor_trialExpired:
      '⚠️ आपका निःशुल्क ट्रायल समाप्त हो गया। सक्रिय रहने के लिए सब्सक्राइब करें।',
    landing_emergencyTitle: 'आपातकालीन मदद',
    landing_emergencyDesc: 'मैकेनिक, एम्बुलेंस, प्लंबर तुरंत खोजें',
    landing_deliveryTitle: 'स्थानीय डिलीवरी',
    landing_deliveryDesc: 'पास की किराना, फार्मेसी से ऑर्डर करें',
    landing_bookingTitle: 'सेवा बुक करें',
    landing_bookingDesc: 'ब्यूटिशियन, दर्जी, रसोइया आपके दरवाजे पर',
    landing_downloadApp: 'ऐप डाउनलोड करें',
    landing_vendorRegister: 'विक्रेताओं के लिए: दुकान रजिस्टर करें और ग्राहक पाएं',
    landing_copyright: '© 2026 आसपास प्रो',
    vendor_view_orders: 'आने वाले ऑर्डर देखें',
    vendor_your_name: 'आपका नाम',
    vendor_name_placeholder: 'Ramesh Kumar',
    vendor_shop_name: 'दुकान का नाम',
    vendor_shop_placeholder: 'Ramesh Tyre Works',
    vendor_category_label: 'कैटेगरी',
    vendor_specify_category: 'अपनी सेवा बताएं',
    vendor_specify_placeholder: 'जैसे: बढ़ई, दर्जी, टिफिन सेवा',
    vendor_specify_hint: 'अपनी सेवा आसान शब्दों में बताएं।',
    vendor_understanding: 'आपकी सेवा समझ रहे हैं...',
    vendor_more_specific: 'कृपया सही कैटेगरी चुनें।',
    vendor_we_think: 'हमें लगता है आप यह चाहते हैं:',
    vendor_help_service: 'मदद सेवा',
    vendor_delivery_service: 'डिलीवरी सेवा',
    vendor_govt_service: '· सरकारी सेवा',
    vendor_confirm: 'ठीक है',
    vendor_confirmed_category: 'चुनी गई कैटेगरी:',
    vendor_how_serve: 'ग्राहकों की सेवा कैसे करते हैं?',
    vendor_mode_visit: '🤝 मैं जाकर मदद करता हूं',
    vendor_mode_visit_eg: 'मैकेनिक, प्लंबर आदि',
    vendor_mode_deliver: '📦 मैं डिलीवरी करता हूं',
    vendor_mode_deliver_eg: 'किराना, दवाई आदि',
    vendor_mode_booking: '📅 मैं बुकिंग लेता हूं',
    vendor_mode_booking_eg: 'ब्यूटीशियन, दर्जी आदि',
    vendor_phone_label: 'फ़ोन (जरूरी)',
    vendor_phone_placeholder: '+91 98xxxxxxxx',
    vendor_phone_hint: '10 अंकों का सही मोबाइल नंबर डालें।',
    vendor_upi_label: 'UPI ID',
    vendor_upi_placeholder: 'name@okbank',
    vendor_upi_hint: 'UPI ऐसा होना चाहिए: handle@bank',
    vendor_note_label: 'ग्राहकों के लिए नोट (वैकल्पिक)',
    vendor_referralCodeLabel: 'रेफरल कोड (वैकल्पिक)',
    vendor_referralCodePlaceholder: 'जैसे MAT-9973',
    vendor_note_placeholder: 'जैसे: शाम 6-8 बजे डिलीवरी। हफ्ते में घर पर आना।',
    vendor_gps_warning:
      'लोकेशन घर से नहीं, दुकान से लें। इससे ग्राहक आपको आसानी से ढूंढ सकते हैं।',
    vendor_capture_location: '📍 दुकान की लोकेशन लें',
    vendor_register_btn: 'रजिस्टर करें',
    vendor_register_hint: 'सही फोन नंबर डालने पर रजिस्ट्रेशन होगा।',
    vendor_or: 'या',
    vendor_already_registered: 'पहले से रजिस्टर हैं? खाता खोजें',
    vendor_find_account_title: 'अपना दुकानदार खाता खोजें',
    vendor_find_account_hint: 'वही फोन नंबर डालें जिससे रजिस्टर किया था',
    vendor_find_btn: 'मेरा खाता खोजें',
    vendor_back_to_reg: '← रजिस्ट्रेशन पर वापस',
    vendor_ready: 'मदद के लिए तैयार',
    vendor_offline_label: 'ऑफलाइन',
    vendor_tap_offline: 'ऑफलाइन होने के लिए दबाएं',
    vendor_offline_active_orders_title: 'आज के लिए सक्रिय ऑर्डर हैं',
    vendor_offline_active_orders_message:
      'ऑफलाइन होने से पहले अपने ग्राहकों से संपर्क करें और उन्हें सूचित करें।',
    vendor_stay_online: 'ऑनलाइन रहें',
    vendor_go_offline_anyway: 'फिर भी ऑफलाइन जाएं',
    vendor_tap_online: 'ऑनलाइन होने के लिए दबाएं',
    vendor_customers_waiting: 'पास के ग्राहक इंतजार कर रहे हैं!',
    vendor_mobile_gps: 'मोबाइल सेवा · लाइव होने पर GPS अपडेट होता है।',
    vendor_verified_pro: 'वेरिफाइड प्रोफेशनल',
    vendor_referEarn: '🎁 रेफर करें और कमाएं',
    vendor_referCopyLink: '📋 लिंक कॉपी करें',
    vendor_referShare: '📤 शेयर करें',
    vendor_referLinkCopied: 'लिंक कॉपी हो गई!',
    vendor_referVendorCredit: (amount: number) =>
      `विक्रेता को रेफर करें → 3 महीने में ₹${amount} क्रेडिट`,
    vendor_referUserCredit: (amount: number) => `यूजर को रेफर करें → ₹${amount} क्रेडिट`,
    liveTracking_callWithCare: 'सावधानी से कॉल करें',
    vendor_pending_label: 'वेरिफिकेशन बाकी है',
    vendor_complete_verification: 'वेरिफिकेशन पूरा करें',
    vendor_verification_shop: 'वेरिफिकेशन और दुकान',
    vendor_close: '✕ बंद करें',
    vendor_verification_heading: 'वेरिफिकेशन',
    vendor_phone_on_file: 'रजिस्टर्ड फोन',
    vendor_not_provided: 'नहीं दिया',
    vendor_upi_bank_match: 'UPI बैंक मिलान',
    vendor_checking: 'चेक हो रहा है…',
    vendor_verify_upi_btn: 'UPI वेरिफाई करें',
    vendor_photo_gps: 'लाइव दुकान फोटो + GPS मिलान',
    vendor_photo_captured: 'फोटो लिया और GPS वेरिफाइड',
    vendor_photo_hint: 'सिर्फ लाइव कैमरा · दुकान से 75 मी. के अंदर',
    vendor_reshoot: 'फिर से फोटो लें',
    vendor_capture: 'फोटो लें',
    vendor_captured_shop: 'दुकान की फोटो ली',
    vendor_badge_approval:
      'हरा "बिज़नेस वेरिफाइड" बैज एडमिन की मंजूरी के बाद चमकता है',
    vendor_approved: '✅ मंजूर',
    vendor_approval_pending: 'बाकी है',
    vendor_update_location: 'दुकान की लोकेशन बदलें',
    vendor_location_reset_warning: 'लोकेशन बदलने पर वेरिफाइड स्टेटस रीसेट होगा।',
    vendor_note_customers: 'ग्राहकों के लिए नोट',
    vendor_note_edit_placeholder: 'जैसे: शाम 6-8 बजे डिलीवरी',
    vendor_saving: 'सेव हो रहा है…',
    vendor_save_note: 'नोट सेव करें',
    vendor_location_set: 'लोकेशन सेट हुई',
    vendor_mismatch_title: 'लोकेशन मेल नहीं खाती',
    myOrders_statusSent: '📤 भेजा गया',
    myOrders_statusSeen: '👀 दुकानदार ने ऑर्डर देखा',
    myOrders_statusNoResponse: '⚠️ अभी तक कोई जवाब नहीं',
    myOrders_statusFulfilled: '✅ दुकानदार ने ऑर्डर पूरा किया',
    myOrders_errCouldNotUpdate: 'अपडेट नहीं हो सका',
    myOrders_errCouldNotCancel: 'रद्द नहीं हो सका',
    myOrders_bookingCancelled: 'बुकिंग रद्द हुई।',
    myOrders_shopFallback: 'दुकान',
    myOrders_backToHome: 'होम पर वापस',
    myOrders_appName: 'आसपास प्रो',
    myOrders_heading: 'मेरे ऑर्डर',
    myOrders_noOrders: 'कोई सक्रिय ऑर्डर नहीं।',
    myOrders_noOrdersHint: 'अपना पहला ऑर्डर भेजने के लिए दुकानदार खोजें!',
    myOrders_findVendors: 'दुकानदार खोजें →',
    myOrders_deliverySlotPrefix: '🕐 ',
    myOrders_locationComeToYou: '🏠 वे आपके पास आएंगे',
    myOrders_locationVisitShop: '🏪 आप उनकी दुकान जाएंगे',
    myOrders_locationTbd: '📞 जगह तय होगी',
    myOrders_apptAround: '📅 लगभग ',
    myOrders_apptConfirmed: '· ✅ दुकानदार ने पुष्टि की',
    myOrders_apptDeclined: '· ❌ दुकानदार ने मना किया',
    myOrders_apptCancelled: '· ❌ दुकानदार ने रद्द किया',
    myOrders_apptAwaiting: '· ⏳ पुष्टि का इंतज़ार',
    myOrders_dismiss: '🗑 हटाएं',
    myOrders_cancelBooking: 'बुकिंग रद्द करें',
    myOrders_sameDayWarning: '⚠️ उसी दिन बदलाव के लिए पहले दुकानदार को कॉल करें',
    myOrders_callThenCancel: '📞 रद्द करने के लिए AI-Bridge से जुड़ें',
    myOrders_callDone: '✅ कॉल हो गई — अब आप बुकिंग रद्द कर सकते हैं',
    myOrders_confirmCancelQ: 'क्या आप वाकई रद्द करना चाहते हैं?',
    myOrders_yesCancel: 'हाँ, रद्द करें',
    myOrders_keepIt: 'रहने दें',
    myOrders_saving: 'सेव हो रहा है…',
    myOrders_delivered: '✅ डिलीवर हुआ! हटाने के लिए दबाएं',
    myOrders_cancelOrder: 'ऑर्डर रद्द करें',
    myOrders_confirmCancelOrderQ: 'क्या आप वाकई यह ऑर्डर रद्द करना चाहते हैं?',
    myOrders_cannotCancel: '🔒 रद्द नहीं हो सकता — दुकानदार इस पर काम कर रहा है',
    myOrders_cancelledByVendor: 'विक्रेता ने रद्द किया',
    myOrders_vendorCancelledDefault: 'विक्रेता ने यह ऑर्डर रद्द कर दिया',
    vendor_stopped_warning:
      'आपका सहायक रुक गया लगता है। क्या वे ठीक हैं? उन्हें कॉल करें।',
    vendor_distance: 'विक्रेता दूर है',
    vendor_last_updated: 'अपडेट',
    user_vendor_offline_title: 'आपका विक्रेता ऑफलाइन हो गया',
    user_vendor_offline_body:
      'आपके ऑर्डर पर असर पड़ सकता है। जरूरत हो तो दूसरा विक्रेता खोजें।',
    settings_vendorVerified: 'दुकानदार सत्यापित ✅',
    settings_removeVerifyConfirm: 'क्या इस दुकानदार का सत्यापन हटाएं?',
    settings_verificationRemoved: 'सत्यापन हटाया गया',
    settings_devMenuUnlocked: 'डेवलपर मेनू अनलॉक हुआ',
    settings_clearDataTitle: 'सभी डेटा हटाएं?',
    settings_clearDataDescription:
      'यह आपका फोन नंबर, सहेजे गए पते, ऑर्डर इतिहास, भाषा और थीम प्राथमिकताएं, और इस डिवाइस से विक्रेता सत्र हटा देगा। यह पूर्ववत नहीं किया जा सकता।',
    settings_clearDataConfirm: 'सब कुछ हटाएं',
    settings_localDataCleared: 'लोकल डेटा साफ हुआ',
    settings_heading: 'सेटिंग्स',
    settings_tagline: 'अपना बनाएं।',
    settings_switchRole: 'भूमिका बदलें',
    settings_switchRoleHintPrefix: 'नीचे का नेविगेशन उपयोग करें — ',
    settings_switchRoleHome: 'होम',
    settings_switchRoleForHelp: ' मदद के लिए,',
    settings_switchRoleVendor: 'दुकानदार',
    settings_switchRoleToEarn: ' कमाई के लिए।',
    settings_myIdentity: 'मेरी पहचान',
    settings_phonePrefix: '📞 ',
    settings_registered: 'पंजीकृत — ऑर्डर सभी डिवाइस पर दिखेंगे',
    settings_noPhone: 'अभी तक फोन नंबर नहीं जुड़ा',
    settings_noPhoneHint: 'पंजीकरण के लिए कोई दुकानदार सेव करें या ऑर्डर भेजें',
    settings_devicePrefix: 'डिवाइस: ',
    settings_deviceEllipsis: '…',
    settings_myDeliveryAddresses: '📍 मेरे डिलीवरी पते',
    settings_noAddresses: 'अभी तक कोई पता सहेजा नहीं गया।',
    settings_shareApp: '📤 ऐप शेयर करें',
    settings_inviteFriend: 'दोस्त को आमंत्रित करें',
    settings_language: 'भाषा',
    settings_accessibility: '♿ अभिगम्यता',
    settings_largeText: 'बड़ा टेक्स्ट',
    settings_largeTextHint: 'ऐप में टेक्स्ट का आकार बढ़ाता है',
    cancelReasons: 'रद्द करने के कारण',
    cancelReasonsSubtitle: 'ऑर्डर रद्द करने पर यूज़र को दिखेगा',
    saveReasons: 'कारण सेव करें',
    theme: 'थीम',
    light: 'लाइट',
    dark: 'डार्क',
    settings_notifications: 'सूचनाएं',
    settings_vibrate: 'नए ऑर्डर पर कंपन',
    settings_sound: 'नए ऑर्डर पर ध्वनि',
    settings_sound_body: 'Android सेटिंग्स में सूचना ध्वनि प्रबंधित करें',
    onboard_notifications_title: 'ऑर्डर तुरंत पाएं',
    onboard_notifications_body:
      'सूचनाएं अनुमति दें ताकि कोई ऑर्डर न छूटे।',
    onboard_allow_notifications: 'सूचनाएं अनुमति दें',
    onboard_skip: 'अभी छोड़ें',
    onboard_location_title: 'अपना स्थान साझा करें',
    onboard_location_body:
      'ग्राहकों को आपको ढूंढने की जरूरत है। सटीक रडार के लिए स्थान अनुमति दें।',
    onboard_allow_location: 'स्थान अनुमति दें',
    onboard_battery_title: 'कोई ऑर्डर न छूटे',
    onboard_battery_body:
      'बैटरी अनुकूलन बंद करें ताकि Aaspaas Pro पृष्ठभूमि में विश्वसनीय चले।',
    onboard_open_settings: 'सेटिंग्स खोलें',
    onboard_battery_skip: 'बाद में करूंगा',
    onboard_camera_title: 'अपनी दुकान सत्यापित करें',
    onboard_camera_body:
      'दुकान की फोटो से विश्वास बैज मिलता है। ग्राहक सत्यापित विक्रेताओं को पसंद करते हैं।',
    onboard_allow_camera: 'कैमरा अनुमति दें',
    onboard_done_title: 'आप तैयार हैं!',
    onboard_done_body: 'ऑर्डर स्वीकार करें और अपना व्यवसाय बढ़ाएं।',
    onboard_get_started: 'शुरू करें',
    settings_myShop: 'मेरी दुकान',
    settings_dotSeparator: ' · ',
    settings_vendorNotePrefix: '📌 ',
    settings_loading: 'लोड हो रहा है...',
    settings_myAnalytics: 'मेरा विश्लेषण',
    settings_totalOrders: 'कुल ऑर्डर',
    settings_thisMonth: 'इस महीने',
    settings_fulfilled: 'पूरे किए',
    settings_declined: 'मना किए',
    settings_adminHealth: 'एडमिन — ऐप स्वास्थ्य',
    settings_adminOnly: 'केवळ आपको दिखता है।',
    settings_orders: 'ऑर्डर',
    settings_allTime: 'सभी समय',
    settings_thisWeek: 'इस हफ्ते',
    settings_today: 'आज',
    settings_vendors: 'दुकानदार',
    settings_total: 'कुल',
    settings_activeToday: 'आज सक्रिय',
    settings_newThisWeek: 'इस हफ्ते नए',
    settings_unverified: 'असत्यापित',
    admin_pendingCategories: '🗂️ लंबित श्रेणियां',
    admin_approve: 'स्वीकृत करें',
    admin_reject: 'अस्वीकार करें',
    admin_noPendingCategories: 'कोई लंबित श्रेणी नहीं',
    settings_vendorVerification: 'दुकानदार सत्यापन',
    settings_unverifiedFirst: 'असत्यापित दुकानदार पहले दिखेंगे।',
    settings_searchPlaceholder: 'नाम, दुकान, फोन से खोजें...',
    settings_noVendorsFound: 'कोई दुकानदार नहीं मिला।',
    settings_live: 'लाइव',
    settings_btnLoading: '...',
    settings_verified: 'सत्यापित',
    settings_trustSecurity: 'विश्वास और सुरक्षा',
    settings_dbConnected: 'डेटाबेस: जुड़ा और सुरक्षित',
    settings_tlsNote: 'सभी डेटा TLS से भेजा जाता है और row-level security से सुरक्षित है।',
    settings_appName: 'आसपास प्रो',
    settings_appTagline: 'मदद, आपके आसपास। अभी।',
    settings_version: 'वर्शन 1.0.0 · भारत के लिए बना',
    settings_copyright: '© 2026 आसपास प्रो',
    settings_devMenu: 'डेवलपर मेनू',
    settings_hideDevMenu: 'डेवलपर मेनू छुपाएं',
    settings_clearMyData: 'मेरा डेटा साफ करें',
    settings_verifyVendor: 'दुकानदार सत्यापित करें',
    settings_check1: 'पंजीकृत फोन पर कॉल किया — व्यक्ति ने उठाया',
    settings_check2: 'नाम कॉल में बताए नाम से मेल खाता है',
    settings_check3: 'दुकानदार को पता है उन्होंने Aaspaas पर रजिस्टर किया है',
    settings_check4: 'दुकान पंजीकृत जगह पर असल में मौजूद है',
    settings_check5: 'दुकान का नाम साइनबोर्ड / उनके कहे से मेल खाता है',
    settings_check6: 'श्रेणी उनकी असल सेवा से मेल खाती है',
    settings_check7: 'सेवा मोड सही है (help / delivery / appointment)',
    settings_check8: 'कोई डुप्लिकेट अकाउंट नहीं मिला (एक ही फोन या दुकान)',
    settings_check9: 'दुकान की फोटो अपलोड है और असली लगती है',
    settings_check10: 'UPI ID सत्यापित है (अगर दिया है)',
    settings_check11: 'कोई संदिग्ध गतिविधि नहीं (तेज़ ऑर्डर, नकली नंबर)',
    settings_check12: 'दुकानदार Aaspaas के उपयोग नियम समझता है',
    settings_verifying: 'सत्यापित हो रहा है...',
    settings_markVerified: '✅ सत्यापित करें',
    settings_cancel: 'रद्द करें',
    parchi_slotAsap: 'जितनी जल्दी हो सके',
    parchi_slotMorning: 'सुबह (12 बजे से पहले)',
    parchi_slotAfternoon: 'दोपहर (12–4 बजे)',
    parchi_slotEvening: 'शाम (4 बजे के बाद)',
    parchi_slotTomorrow: 'कल',
    parchi_errNoOrder: 'कृपया अपना ऑर्डर लिखें।',
    parchi_errNoAddress: 'कृपया डिलीवरी पता जोड़ें।',
    parchi_errNoDateTime: 'कृपया अपॉइंटमेंट की तारीख और समय चुनें।',
    parchi_locationComeToMe: ' [मेरे घर आएं]',
    parchi_locationVisitShop: ' [मैं दुकान आऊंगा]',
    parchi_locationTbd: ' [जगह तय होगी]',
    parchi_errCouldNotSend: 'ऑर्डर नहीं भेजा जा सका',
    parchi_toastBookingSuccess: '📅 बुकिंग अनुरोध भेजा!',
    parchi_toastOrderSuccess: '✅ ऑर्डर भेजा! वे जल्द देखेंगे।',
    parchi_slotAsapEmoji: '🚀 जितनी जल्दी हो सके',
    parchi_slotMorningEmoji: '🌅 सुबह (12 बजे से पहले)',
    parchi_slotAfternoonEmoji: '🌞 दोपहर (12–4 बजे)',
    parchi_slotEveningEmoji: '🌆 शाम (4 बजे के बाद)',
    parchi_slotTomorrowEmoji: '📅 कल',
    parchi_titleBook: 'बुकिंग: ',
    parchi_titleOrder: 'ऑर्डर: ',
    parchi_onlineBooking: '🟢 ऑनलाइन — बुकिंग जल्द पुष्टि होगी',
    parchi_offlineBooking: '⚫ ऑफलाइन — वापस आने पर पुष्टि करेंगे',
    parchi_onlineOrder: '🟢 ऑनलाइन — जल्द देखेंगे',
    parchi_offlineOrder: '⚫ ऑफलाइन — वापस आने पर देखेंगे',
    parchi_vendorNotePrefix: '📌 ',
    parchi_deliveryAddress: 'डिलीवरी पता',
    parchi_loadingAddresses: 'पते लोड हो रहे हैं...',
    parchi_useDifferentAddress: '+ अलग पता उपयोग करें',
    parchi_addressPlaceholder: 'जैसे: फ्लैट 4B, ग्रीन पार्क, वॉटर टैंक के पास',
    parchi_saveAddress: 'अगली बार के लिए यह पता सेव करें',
    parchi_whereQuestion: '📍 कहाँ?',
    parchi_locationComeToMeBtn: '🏠 मेरे घर आएं',
    parchi_locationVisitBtn: '🏪 मैं आऊंगा',
    parchi_locationDecideLater: '📞 बाद में तय करें',
    parchi_whenAppt: '📅 कब चाहिए?',
    parchi_dateLabel: 'तारीख',
    parchi_timeLabel: 'समय',
    parchi_whenDelivery: '🕐 कब चाहिए?',
    parchi_orderLabel: 'आपका ऑर्डर',
    parchi_placeholderAppt: 'कोई खास बात?\nजैसे: फुल फेशियल, 2 लोग, ग्राउंड फ्लोर',
    parchi_placeholderOrder: 'ऑर्डर लिखें...\nजैसे: 1kg आटा, 2 साबुन, Colgate टूथपेस्ट',
    parchi_charSeparator: ' / ',
    parchi_cancellationAppt:
      'ℹ️ बुकिंग के दिन से पहले मुफ्त रद्द। उसी दिन बदलाव के लिए पहले कॉल करें।',
    parchi_cancellationOrder:
      'ℹ️ यह ऑर्डर तभी रद्द हो सकता है जब दुकानदार ने अभी तक न देखा हो।',
    parchi_btnConfirmBooking: '📅 बुकिंग पक्की करें',
    parchi_btnSendOrder: '📋 ऑर्डर भेजें',
    parchi_btnCancel: 'रद्द करें',
    incoming_errCouldNotUpdate: 'ऑर्डर अपडेट नहीं हो सका',
    incoming_errCouldNotUpdateAppt: 'अपॉइंटमेंट अपडेट नहीं हो सकी',
    incoming_apptConfirmed: '✅ अपॉइंटमेंट पक्की हुई!',
    incoming_apptDeclined: 'अपॉइंटमेंट नकारी।',
    incoming_errCouldNotCancel: 'रद्द नहीं हो सका',
    incoming_bookingCancelled: 'बुकिंग रद्द हुई।',
    incoming_statusNew: 'नया',
    incoming_statusSeen: 'देखा',
    incoming_statusDone: 'पूरा ✅',
    incoming_heading: '📋 आने वाले ऑर्डर',
    incoming_unreadCap: '99+',
    incoming_empty: 'अभी कोई ऑर्डर नहीं!',
    incoming_addressPrefix: '📍 ',
    incoming_slotPrefix: '🕐 ',
    incoming_locationComeToYou: '🏠 आपके पास आएंगे',
    incoming_locationVisitShop: '🏪 आपकी दुकान आएंगे',
    incoming_locationTbd: '📞 जगह तय होगी',
    incoming_apptAround: '📅 लगभग ',
    incoming_btnConfirm: '✅ पुष्टि करें',
    incoming_btnDecline: '❌ मना करें',
    incoming_bannerConfirmed: '✅ अपॉइंटमेंट पक्की',
    incoming_bannerDeclined: '❌ अपॉइंटमेंट नकारी',
    incoming_cancelAppt: 'अपॉइंटमेंट रद्द करें',
    incoming_sameDayWarning: '⚠️ उसी दिन रद्द — पहले ग्राहक को कॉल करें',
    incoming_callThenCancel: '📞 रद्द करने के लिए AI-Bridge से जुड़ें',
    incoming_callDone: '✅ कॉल हो गई — अब रद्द कर सकते हैं',
    incoming_callBridge: '📞 AI-Bridge से जुड़ें',
    incoming_saving: 'सेव हो रहा है…',
    incoming_markDone: '✅ पूरा करें',
    incoming_btnAccept: '✅ स्वीकार करें',
    status_accepted: 'विक्रेता ने स्वीकार किया — रास्ते में',
    order_already_taken: 'यह ऑर्डर पहले ही किसी अन्य विक्रेता ने स्वीकार कर लिया',
    cancelOrder: 'ऑर्डर रद्द करें',
    cancelReason: 'रद्द क्यों कर रहे हैं?',
    confirmCancel: 'रद्द करें',
    orderCancelled: 'ऑर्डर रद्द हुआ',
    other: 'अन्य',
    cancelReasonPlaceholder: 'कारण लिखें...',
    editOrder: 'ऑर्डर बदलें',
    saveChanges: 'बदलाव सेव करें',
    orderUpdated: 'ऑर्डर अपडेट हुआ',
    vendorSeenWarning:
      'विक्रेता ने यह ऑर्डर देख लिया है। बदलाव की सूचना उन्हें मिलेगी।',
    rating_errCouldNotSave: 'रेटिंग सेव नहीं हो सकी',
    rating_errCouldNotSaveFeedback: 'फीडबैक सेव नहीं हो सका',
    rating_heading: 'आपका ऑर्डर कैसा रहा?',
    rating_btnDelivered: '📦 समय पर डिलीवर हुआ',
    rating_btnHelped: '✅ उन्होंने मेरी मदद की',
    rating_btnIssue: '⚠️ कोई समस्या थी',
    rating_helperText: 'बंद करने के लिए फीडबैक दें',
  },
  mr: {
    appName: 'आसपास प्रो',
    tagline: 'मदत, तुमच्या आसपास. आत्ताच.',
    taglineSub: 'तुमच्या परिसराचा स्मार्ट सहाय्यक।',
    sos_title: 'SOS',
    sos_subtitle: 'मदतीसाठी दाबा',
    aiSearch: 'AI शोध',
    searchPlaceholder: 'मदत शोधा (उदा., मेकॅनिक, रुग्णवाहिका, किल्लीवाला)',
    findingMatch: 'उत्तम पर्याय शोधत आहोत...',
    voiceNotSupported: 'या ब्राउझरमध्ये व्हॉइस सपोर्ट नाही. Android वर Chrome वापरा.',
    voiceError: 'ऐकू आले नाही. पुन्हा प्रयत्न करा.',
    myNeighbourhood: 'माझी सेव्ह केलेली लिस्ट',
    online: 'ऑनलाइन',
    offline: 'ऑफलाइन',
    nav_home: 'होम',
    nav_vendor: 'विक्रेता',
    nav_settings: 'सेटिंग्स',
    category_mode_help: '🚨 आणीबाणी आणि मदत',
    category_mode_delivery: '🛒 डिलिव्हरी',
    category_mode_appointment: '✂️ सेवा बुक करा',
    activeOrders: (n: number) => `📋 तुमचे ${n} ॲक्टिव्ह ऑर्डर्स आहेत → पहा`,
    yourActiveOrders: '📋 तुमचे सक्रिय ऑर्डर्स →',
    sendNewOrder: '📋 नवीन ऑर्डर पाठवा',
    sendOrder: '📋 ऑर्डर पाठवा',
    yourActiveBookings: '📅 तुमच्या ॲक्टिव्ह बुकिंग्ज →',
    bookAgain: '📅 पुन्हा बुक करा',
    bookService: '📅 सेवा बुक करा',
    connectAiBridge: 'AI-Bridge द्वारे कनेक्ट व्हा',
    cancel: 'रद्द करा',
    removeFromNeighbourhood: '🗑 सेव्ह केलेल्या लिस्टधून काढा',
    couldNotRemove: 'काढता आले नाही',
    removedFromNeighbourhood: 'सेव्ह केलेल्या लिस्टधून काढले गेले',
    aiBridge: 'AI-Bridge',
    briefingVendor: 'AI द्वारे विक्रेत्याला माहिती दिली जात आहे…',
    aiBriefUnavailable: 'AI माहिती उपलब्ध नाही — थेट कॉल करा',
    yourCallBrief: 'तुमची कॉल माहिती',
    callNow: 'आत्ताच कॉल करा',
    ai_bridge_call_limited: 'कॉल X मिनिटांपर्यंत मर्यादित',
    ai_bridge_connecting: 'तुमचा कॉल कनेक्ट होत आहे... कृपया थांबा',
    ai_bridge_call_failed: 'कॉल अयशस्वी. पुन्हा प्रयत्न करा.',
    ai_bridge_call_now: '📞 आत्ताच कॉल करा',
    radar_connection_error: 'कनेक्शन त्रुटी',
    radar_all_emergencies: 'सर्व आणीबाणी',
    radar_back_home: 'होमवर जा',
    radar_expanding_scan: 'शोध वाढवत आहे',
    radar_scanning_area: 'क्षेत्र स्कॅन होत आहे',
    radar_finding_nearby: 'जवळपासचे शोधत आहे ',
    radar_searching_within: 'शोध सुरू आहे ',
    radar_km: ' किमी',
    radar_live: 'लाइव्ह रडार',
    radar_match: 'निकाल',
    radar_matches: 'निकाल',
    radar_found: ' सापडले',
    radar_showing_within: 'जवळपासची मदत दाखवत आहे ',
    radar_no_helpers_15: '15 किमीत कोणी सहाय्यक नाही',
    radar_no_helpers_area: 'तुमच्या परिसरात अजून कोणी सहाय्यक नाही. Aaspaas Pro वाढत आहे — लवकरच पुन्हा तपासा किंवा वेगळी श्रेणी वापरा.',
    radar_expand_25: '25 किमीपर्यंत वाढवा',
    radar_expand_50: '50 किमीपर्यंत वाढवा',
    radar_no_private: 'सध्या कोणी खाजगी सहाय्यक ऑनलाइन नाही',
    radar_official_services: 'तुम्ही खाली सरकारी आपत्कालीन सेवांशी संपर्क करू शकता.',
    radar_helped: 'मदत केली ',
    radar_person: 'व्यक्ती',
    radar_people: 'लोक',
    radar_orders_served: ' ऑर्डर पूर्ण केले',
    radar_on_time: '% वेळेवर',
    radar_location_unknown: 'स्थान अज्ञात',
    radar_est_arrival: 'अंदाजे आगमन ~',
    radar_min: ' मिनिट',
    radar_verification_progress: 'पडताळणी सुरू आहे — सावधगिरीने पुढे जा.',
    radar_not_verified: 'सावधान: ओळख पडताळलेली नाही — स्वतःच्या जबाबदारीवर संपर्क करा.',
    radar_connect_ai: 'AI-Bridge द्वारे जोडा',
    radar_your_brief: 'तुमचा कॉल सारांश',
    radar_cancel: 'रद्द करा',
    radar_booking_requested: 'बुकिंग विनंती पाठवली',
    radar_order_sent: 'ऑर्डर पाठवला',
    radar_book_again: 'पुन्हा बुक करा',
    radar_send_new_order: 'नवीन ऑर्डर पाठवा',
    radar_book_service: 'सेवा बुक करा',
    radar_send_order: 'ऑर्डर पाठवा',
    radar_marked: 'नोंदवले!',
    radar_delivered_on_time: 'वेळेवर डिलिव्हर झाले',
    radar_he_helped: 'यांनी मला मदत केली',
    radar_save_as: 'माझे ',
    radar_vendor_fallback: 'विक्रेता',
    radar_saved_success: 'सेव्ह झाले! होम स्क्रीनवर पाहा.',
    radar_could_not_save: 'सेव्ह होऊ शकले नाही',
    radar_thank_community: 'धन्यवाद! यामुळे समुदायाला मदत होते.',
    radar_signal_unknown: 'सिग्नल: अज्ञात',
    radar_signal_strong: 'सिग्नल: मजबूत',
    radar_last_active: 'शेवटचे सक्रिय: ',
    radar_mins_ago: ' मिनिटांपूर्वी',
    radar_h_ago: 'तासांपूर्वी',
    radar_d_ago: 'दिवसांपूर्वी',
    radar_govt_help: 'सरकारी मदत',
    radar_tap_to_open: 'उघडण्यासाठी टॅप करा · मुख्य लाइन: ',
    radar_local_police: 'स्थानिक पोलीस',
    radar_police_tagline: 'जवळचे पोलीस स्टेशन',
    vendor_verified_title: 'तुम्ही व्हेरिफाइड आहात!',
    vendor_verified_body: 'तुमचा हिरवा बॅज लाइव्ह आहे. ग्राहक तुमच्यावर अधिक विश्वास ठेवतात.',
    vendor_verified_cta: 'ऑनलाइन होण्यासाठी पॉवर बटन दाबा.',
    vendor_submitted_title: 'व्हेरिफिकेशन सादर झाली',
    vendor_submitted_body:
      'आमची टीम 24 तासांत तुमची माहिती तपासेल. तोपर्यंत — ऑनलाइन होण्यासाठी पॉवर बटन दाबा!',
    vendor_geo_not_supported: 'या डिव्हाइसवर जिओलोकेशन उपलब्ध नाही.',
    vendor_location_captured: 'दुकानाचे स्थान मिळाले',
    vendor_location_failed: 'स्थान मिळाले नाही',
    vendor_name_invalid: 'हे नाव बरोबर वाटत नाही',
    vendor_name_invalid_body: 'कृपया तुमचे खरे नाव टाका (फक्त अक्षरे).',
    vendor_shopname_invalid: 'दुकानाचे नाव बरोबर वाटत नाही',
    vendor_shopname_invalid_body: 'कृपया खरे दुकानाचे नाव टाका.',
    vendor_specify_service: 'तुमची सेवा सांगा',
    vendor_specify_service_body: "'इतर' निवडताना, तुमची सेवा साध्या शब्दांत सांगा.",
    vendor_choose_service: 'ग्राहकांची सेवा कशी करता?',
    vendor_choose_service_body: 'भेट व मदत किंवा डिलिव्हरी यापैकी निवडा.',
    vendor_phone_invalid: 'चुकीचा फोन नंबर',
    vendor_phone_invalid_body: '10 अंकी बरोबर मोबाइल नंबर टाका.',
    vendor_upi_invalid: 'चुकीचा UPI ID',
    vendor_upi_invalid_body: 'UPI असे असावे: ramesh@okicici',
    vendor_welcome_title: 'स्वागत आहे!',
    vendor_welcome_body: 'ओळख जोडली. व्हेरिफाइड होण्यासाठी दुकानाचा फोटो घ्या.',
    vendor_welcome_back: 'पुन्हा स्वागत आहे!',
    vendor_not_found: 'या नंबरने कोणताही विक्रेता सापडला नाही. आधी नोंदणी करा.',
    vendor_location_required: 'लाइव्ह होण्यासाठी लोकेशन आवश्यक आहे',
    vendor_location_required_body: 'ऑनलाइन होताना नवीन GPS लोकेशन हवे.',
    vendor_status_failed: 'स्टेटस अपडेट झाला नाही',
    vendor_you_are_live: 'तुम्ही लाइव्ह आहात ✨',
    vendor_you_are_offline: 'तुम्ही ऑफलाइन आहात',
    vendor_live_body: 'लाइव्ह लोकेशन अपडेट झाले. जवळचे ग्राहक तुम्हाला शोधू शकतात.',
    vendor_live_body_short: 'जवळचे ग्राहक तुम्हाला शोधू शकतात.',
    vendor_offline_body: 'नवीन ऑर्डर मिळणार नाहीत.',
    vendor_upi_format_invalid: 'चुकीचा UPI फॉर्मेट',
    vendor_upi_format_body: 'handle@bank असायला हवे',
    vendor_upi_check_failed: 'UPI तपासता आले नाही',
    vendor_upi_verified: 'UPI व्हेरिफाइड · ',
    vendor_upi_bank_valid: 'बँक हँडल बरोबर वाटते.',
    vendor_set_location_first: 'आधी दुकानाचे लोकेशन सेट करा',
    vendor_set_location_first_body: "फोटो घेण्यापूर्वी 'दुकान लोकेशन अपडेट करा' दाबा.",
    vendor_upload_failed: 'अपलोड झाले नाही',
    vendor_save_verification_failed: 'व्हेरिफिकेशन सेव्ह झाले नाही',
    vendor_photo_verified: 'दुकानाचा फोटो व्हेरिफाइड',
    vendor_green_badge_live: 'हिरवा बॅज लाइव्ह आहे.',
    vendor_awaiting_admin: 'हिरव्या बॅजसाठी एडमिनची मंजुरी बाकी आहे.',
    vendor_location_reset_confirm:
      'लोकेशन बदलल्यास दुकानाची पुन्हा व्हेरिफिकेशन होईल. सुरू ठेवायचे?',
    vendor_location_update_failed: 'लोकेशन अपडेट झाले नाही',
    vendor_reverification_required: 'पुन्हा व्हेरिफिकेशन आवश्यक आहे',
    vendor_reverification_body: 'व्हेरिफाइड स्टेटस परत मिळवण्यासाठी नवीन दुकानाचा फोटो घ्या.',
    vendor_location_updated: 'लोकेशन अपडेट झाले',
    vendor_location_updated_body: 'तुमच्या दुकानाचे लोकेशन सेव्ह झाले.',
    vendor_note_save_failed: 'नोट सेव्ह झाला नाही',
    vendor_note_saved: 'नोट सेव्ह झाला!',
    vendor_back_home: 'होमवर जा',
    vendor_mode_title: 'विक्रेता मोड',
    vendor_tagline: 'तुमच्या कौशल्यातून कमवा.',
    vendor_trialDaysLeft: (days: number) => `🎁 मोफत ट्रायल: ${days} दिवस बाकी`,
    vendor_trialExpired:
      '⚠️ तुमचा मोफत ट्रायल संपला. सक्रिय राहण्यासाठी सबस्क्राइब करा.',
    landing_emergencyTitle: 'आणीबाणी मदत',
    landing_emergencyDesc: 'मेकॅनिक, रुग्णवाहिका, प्लंबर लगेच शोधा',
    landing_deliveryTitle: 'स्थानिक डिलिव्हरी',
    landing_deliveryDesc: 'जवळच्या किराणा, फार्मसीकडून ऑर्डर करा',
    landing_bookingTitle: 'सेवा बुक करा',
    landing_bookingDesc: 'ब्युटिशियन, दर्जी, स्वयंपाकी तुमच्या दाराशी',
    landing_downloadApp: 'अ‍ॅप डाउनलोड करा',
    landing_vendorRegister: 'विक्रेत्यांसाठी: दुकान नोंदणी करा आणि ग्राहक मिळवा',
    landing_copyright: '© 2026 आसपास प्रो',
    vendor_view_orders: 'येणारे ऑर्डर पाहा',
    vendor_your_name: 'तुमचे नाव',
    vendor_name_placeholder: 'Ramesh Kumar',
    vendor_shop_name: 'दुकानाचे नाव',
    vendor_shop_placeholder: 'Ramesh Tyre Works',
    vendor_category_label: 'श्रेणी',
    vendor_specify_category: 'तुमची सेवा सांगा',
    vendor_specify_placeholder: 'उदा. सुतार, शिंपी, टिफिन सेवा',
    vendor_specify_hint: 'तुमची सेवा साध्या शब्दांत सांगा.',
    vendor_understanding: 'तुमची सेवा समजत आहे...',
    vendor_more_specific: 'कृपया योग्य श्रेणी निवडा.',
    vendor_we_think: 'आम्हाला वाटते तुम्हाला हे म्हणायचे आहे:',
    vendor_help_service: 'मदत सेवा',
    vendor_delivery_service: 'डिलिव्हरी सेवा',
    vendor_govt_service: '· सरकारी सेवा',
    vendor_confirm: 'ठीक आहे',
    vendor_confirmed_category: 'निवडलेली श्रेणी:',
    vendor_how_serve: 'ग्राहकांची सेवा कशी करता?',
    vendor_mode_visit: '🤝 मी जाऊन मदत करतो',
    vendor_mode_visit_eg: 'मेकॅनिक, प्लंबर इ.',
    vendor_mode_deliver: '📦 मी डिलिव्हरी करतो',
    vendor_mode_deliver_eg: 'किराणा, फार्मसी इ.',
    vendor_mode_booking: '📅 मी बुकिंग घेतो',
    vendor_mode_booking_eg: 'ब्युटिशियन, शिंपी इ.',
    vendor_phone_label: 'फोन (आवश्यक)',
    vendor_phone_placeholder: '+91 98xxxxxxxx',
    vendor_phone_hint: '10 अंकी बरोबर मोबाइल नंबर टाका.',
    vendor_upi_label: 'UPI ID',
    vendor_upi_placeholder: 'name@okbank',
    vendor_upi_hint: 'UPI असे असावे: handle@bank',
    vendor_note_label: 'ग्राहकांसाठी नोट (ऐच्छिक)',
    vendor_referralCodeLabel: 'रेफरल कोड (ऐच्छिक)',
    vendor_referralCodePlaceholder: 'उदा. MAT-9973',
    vendor_note_placeholder: 'उदा. संध्याकाळी 6-8 डिलिव्हरी. आठवड्यात घरभेट.',
    vendor_gps_warning:
      'लोकेशन घरातून नाही, दुकानातून घ्या. यामुळे ग्राहक तुम्हाला सहज शोधू शकतात.',
    vendor_capture_location: '📍 दुकानाचे लोकेशन घ्या',
    vendor_register_btn: 'नोंदणी करा',
    vendor_register_hint: 'बरोबर फोन नंबर टाकल्यावर नोंदणी होईल.',
    vendor_or: 'किंवा',
    vendor_already_registered: 'आधीच नोंदणी केली? खाते शोधा',
    vendor_find_account_title: 'तुमचे विक्रेता खाते शोधा',
    vendor_find_account_hint: 'नोंदणी केलेला फोन नंबर टाका',
    vendor_find_btn: 'माझे खाते शोधा',
    vendor_back_to_reg: '← नोंदणीवर परत',
    vendor_ready: 'मदत करण्यास तैयार',
    vendor_offline_label: 'ऑफलाइन',
    vendor_tap_offline: 'ऑफलाइन होण्यासाठी दाबा',
    vendor_offline_active_orders_title: 'आजचे सक्रिय ऑर्डर आहेत',
    vendor_offline_active_orders_message:
      'ऑफलाइन जाण्यापूर्वी ग्राहकांशी संपर्क साधून त्यांना कळवा.',
    vendor_stay_online: 'ऑनलाइन राहा',
    vendor_go_offline_anyway: 'तरीही ऑफलाइन जा',
    vendor_tap_online: 'ऑनलाइन होण्यासाठी दाबा',
    vendor_customers_waiting: 'जवळचे ग्राहक वाट पाहत आहेत!',
    vendor_mobile_gps: 'मोबाइल सेवा · लाइव्ह होताना GPS अपडेट होते.',
    vendor_verified_pro: 'व्हेरिफाइड प्रोफेशनल',
    vendor_referEarn: '🎁 रेफर करा आणि कमवा',
    vendor_referCopyLink: '📋 लिंक कॉपी करा',
    vendor_referShare: '📤 शेअर करा',
    vendor_referLinkCopied: 'लिंक कॉपी झाली!',
    vendor_referVendorCredit: (amount: number) =>
      `विक्रेत्याला रेफर करा → 3 महिन्यांत ₹${amount} क्रेडिट`,
    vendor_referUserCredit: (amount: number) => `युजरला रेफर करा → ₹${amount} क्रेडिट`,
    liveTracking_callWithCare: 'काळजीपूर्वक कॉल करा',
    vendor_pending_label: 'व्हेरिफिकेशन बाकी आहे',
    vendor_complete_verification: 'व्हेरिफिकेशन पूर्ण करा',
    vendor_verification_shop: 'व्हेरिफिकेशन आणि दुकान',
    vendor_close: '✕ बंद करा',
    vendor_verification_heading: 'व्हेरिफिकेशन',
    vendor_phone_on_file: 'नोंदणीकृत फोन',
    vendor_not_provided: 'दिले नाही',
    vendor_upi_bank_match: 'UPI बँक जुळणी',
    vendor_checking: 'तपासत आहे…',
    vendor_verify_upi_btn: 'UPI व्हेरिफाय करा',
    vendor_photo_gps: 'थेट दुकान फोटो + GPS जुळणी',
    vendor_photo_captured: 'फोटो घेतला आणि GPS व्हेरिफाइड',
    vendor_photo_hint: 'फक्त लाइव्ह कॅमेरा · दुकानापासून 75 मी. आत',
    vendor_reshoot: 'पुन्हा फोटो घ्या',
    vendor_capture: 'फोटो घ्या',
    vendor_captured_shop: 'दुकानाचा फोटो घेतला',
    vendor_badge_approval:
      'हिरवा "बिझनेस व्हेरिफाइड" बॅज एडमिन मंजुरीनंतर चमकतो',
    vendor_approved: '✅ मंजूर',
    vendor_approval_pending: 'बाकी आहे',
    vendor_update_location: 'दुकानाचे लोकेशन बदला',
    vendor_location_reset_warning: 'लोकेशन बदलल्यास व्हेरिफाइड स्टेटस रीसेट होईल.',
    vendor_note_customers: 'ग्राहकांसाठी नोट',
    vendor_note_edit_placeholder: 'उदा. संध्याकाळी 6-8 डिलिव्हरी',
    vendor_saving: 'सेव्ह होत आहे…',
    vendor_save_note: 'नोट सेव्ह करा',
    vendor_location_set: 'लोकेशन सेट झाले',
    vendor_mismatch_title: 'लोकेशन जुळत नाही',
    myOrders_statusSent: '📤 पाठवले',
    myOrders_statusSeen: '👀 विक्रेत्याने ऑर्डर पाहिला',
    myOrders_statusNoResponse: '⚠️ अद्याप प्रतिसाद नाही',
    myOrders_statusFulfilled: '✅ विक्रेत्याने ऑर्डर पूर्ण केला',
    myOrders_errCouldNotUpdate: 'अपडेट होऊ शकले नाही',
    myOrders_errCouldNotCancel: 'रद्द होऊ शकले नाही',
    myOrders_bookingCancelled: 'बुकिंग रद्द झाली.',
    myOrders_shopFallback: 'दुकान',
    myOrders_backToHome: 'मुख्यपृष्ठावर परत',
    myOrders_appName: 'आसपास प्रो',
    myOrders_heading: 'माझे ऑर्डर',
    myOrders_noOrders: 'कोणतेही सक्रिय ऑर्डर नाही.',
    myOrders_noOrdersHint: 'तुमचा पहिला ऑर्डर पाठवण्यासाठी विक्रेता शोधा!',
    myOrders_findVendors: 'विक्रेते शोधा →',
    myOrders_deliverySlotPrefix: '🕐 ',
    myOrders_locationComeToYou: '🏠 ते तुमच्याकडे येतील',
    myOrders_locationVisitShop: '🏪 तुम्ही त्यांच्या दुकानात जाल',
    myOrders_locationTbd: '📞 ठिकाण ठरवायचे आहे',
    myOrders_apptAround: '📅 साधारण ',
    myOrders_apptConfirmed: '· ✅ विक्रेत्याने पुष्टी केली',
    myOrders_apptDeclined: '· ❌ विक्रेत्याने नकार दिला',
    myOrders_apptCancelled: '· ❌ विक्रेत्याने रद्द केले',
    myOrders_apptAwaiting: '· ⏳ पुष्टीची प्रतीक्षा',
    myOrders_dismiss: '🗑 काढा',
    myOrders_cancelBooking: 'बुकिंग रद्द करा',
    myOrders_sameDayWarning: '⚠️ त्याच दिवशी बदल करण्यासाठी आधी विक्रेत्याला कॉल करा',
    myOrders_callThenCancel: '📞 रद्द करण्यासाठी AI-Bridge शी जोडा',
    myOrders_callDone: '✅ कॉल झाली — आता तुम्ही बुकिंग रद्द करू शकता',
    myOrders_confirmCancelQ: 'तुम्हाला खरोखर रद्द करायचे आहे का?',
    myOrders_yesCancel: 'होय, रद्द करा',
    myOrders_keepIt: 'ठेवा',
    myOrders_saving: 'जतन होत आहे…',
    myOrders_delivered: '✅ डिलिव्हर झाले! काढण्यासाठी दाबा',
    myOrders_cancelOrder: 'ऑर्डर रद्द करा',
    myOrders_confirmCancelOrderQ: 'तुम्हाला खरोखर हा ऑर्डर रद्द करायचा आहे का?',
    myOrders_cannotCancel: '🔒 रद्द होणार नाही — विक्रेता आधीच काम करत आहे',
    myOrders_cancelledByVendor: 'विक्रेत्याने रद्द केले',
    myOrders_vendorCancelledDefault: 'विक्रेत्याने हा ऑर्डर रद्द केला',
    vendor_stopped_warning:
      'तुमचा मदतनीस थांबला असल्यासारखे वाटते. ते ठीक आहेत का? कॉल करा.',
    vendor_distance: 'विक्रेता दूर आहे',
    vendor_last_updated: 'अपडेट',
    user_vendor_offline_title: 'तुमचा विक्रेता ऑफलाइन झाला',
    user_vendor_offline_body:
      'तुमच्या ऑर्डरवर परिणाम होऊ शकतो. गरज असल्यास दुसरा विक्रेता शोधा.',
    settings_vendorVerified: 'विक्रेता सत्यापित ✅',
    settings_removeVerifyConfirm: 'या विक्रेत्याचे सत्यापन काढायचे का?',
    settings_verificationRemoved: 'सत्यापन काढले',
    settings_devMenuUnlocked: 'डेव्हलपर मेनू अनलॉक झाला',
    settings_clearDataTitle: 'सर्व डेटा हटवायचा?',
    settings_clearDataDescription:
      'हे तुमचा फोन नंबर, जतन केलेले पत्ते, ऑर्डर इतिहास, भाषा आणि थीम प्राधान्ये आणि या डिव्हाइसवरून विक्रेता सत्र काढून टाकेल. हे पूर्ववत केले जाऊ शकत नाही.',
    settings_clearDataConfirm: 'सर्व हटवा',
    settings_localDataCleared: 'स्थानिक डेटा साफ झाला',
    settings_heading: 'सेटिंग्ज',
    settings_tagline: 'तुमचे करा.',
    settings_switchRole: 'भूमिका बदला',
    settings_switchRoleHintPrefix: 'खालील नेव्हिगेशन वापरा — ',
    settings_switchRoleHome: 'होम',
    settings_switchRoleForHelp: ' मदतीसाठी,',
    settings_switchRoleVendor: 'विक्रेता',
    settings_switchRoleToEarn: ' कमाईसाठी.',
    settings_myIdentity: 'माझी ओळख',
    settings_phonePrefix: '📞 ',
    settings_registered: 'नोंदणीकृत — ऑर्डर सर्व डिव्हाइसवर दिसतील',
    settings_noPhone: 'अद्याप फोन नोंदणी नाही',
    settings_noPhoneHint: 'नोंदणीसाठी विक्रेता जतन करा किंवा ऑर्डर पाठवा',
    settings_devicePrefix: 'डिव्हाइस: ',
    settings_deviceEllipsis: '…',
    settings_myDeliveryAddresses: '📍 माझे डिलिव्हरी पत्ते',
    settings_noAddresses: 'अद्याप कोणतेही पत्ते जतन केलेले नाहीत.',
    settings_shareApp: '📤 अ‍ॅप शेअर करा',
    settings_inviteFriend: 'मित्राला आमंत्रित करा',
    settings_language: 'भाषा',
    settings_accessibility: '♿ प्रवेशयोग्यता',
    settings_largeText: 'मोठा मजकूर',
    settings_largeTextHint: 'अ‍ॅपमध्ये मजकूराचा आकार वाढवतो',
    cancelReasons: 'रद्द करण्याची कारणे',
    cancelReasonsSubtitle: 'ऑर्डर रद्द केल्यावर वापरकर्त्याला दिसेल',
    saveReasons: 'कारण सेव्ह करा',
    theme: 'थीम',
    light: 'लाइट',
    dark: 'डार्क',
    settings_notifications: 'सूचना',
    settings_vibrate: 'नवीन ऑर्डरवर कंपन',
    settings_sound: 'नवीन ऑर्डरवर आवाज',
    settings_sound_body: 'Android सेटिंग्जमध्ये सूचना आवाज व्यवस्थापित करा',
    onboard_notifications_title: 'ऑर्डर लगेच मिळवा',
    onboard_notifications_body:
      'सूचना परवानगी द्या जेणेकरून कोणताही ऑर्डर चुकणार नाही.',
    onboard_allow_notifications: 'सूचना परवानगी द्या',
    onboard_skip: 'आत्ता वगळा',
    onboard_location_title: 'तुमचे स्थान शेअर करा',
    onboard_location_body:
      'ग्राहकांना तुम्हाला शोधावे लागते. अचूक रडारसाठी स्थान परवानगी द्या.',
    onboard_allow_location: 'स्थान परवानगी द्या',
    onboard_battery_title: 'कोणताही ऑर्डर चुकू देऊ नका',
    onboard_battery_body:
      'बॅटरी ऑप्टिमायझेशन बंद करा जेणेकरून Aaspaas Pro पार्श्वभूमीत विश्वासार्ह चालेल.',
    onboard_open_settings: 'सेटिंग्ज उघडा',
    onboard_battery_skip: 'नंतर करेन',
    onboard_camera_title: 'तुमचे दुकान सत्यापित करा',
    onboard_camera_body:
      'दुकानाचा फोटो विश्वास बॅज मिळवतो. ग्राहक सत्यापित विक्रेत्यांना प्राधान्य देतात.',
    onboard_allow_camera: 'कॅमेरा परवानगी द्या',
    onboard_done_title: 'तुम्ही तयार आहात!',
    onboard_done_body: 'ऑर्डर स्वीकारा आणि व्यवसाय वाढवा.',
    onboard_get_started: 'सुरू करा',
    settings_myShop: 'माझे दुकान',
    settings_dotSeparator: ' · ',
    settings_vendorNotePrefix: '📌 ',
    settings_loading: 'लोड होत आहे...',
    settings_myAnalytics: 'माझे विश्लेषण',
    settings_totalOrders: 'एकूण ऑर्डर',
    settings_thisMonth: 'या महिन्यात',
    settings_fulfilled: 'पूर्ण केले',
    settings_declined: 'नाकारले',
    settings_adminHealth: 'अॅडमिन — अॅप आरोग्य',
    settings_adminOnly: 'फक्त तुम्हाला दिसते.',
    settings_orders: 'ऑर्डर',
    settings_allTime: 'सर्व वेळ',
    settings_thisWeek: 'या आठवड्यात',
    settings_today: 'आज',
    settings_vendors: 'विक्रेते',
    settings_total: 'एकूण',
    settings_activeToday: 'आज सक्रिय',
    settings_newThisWeek: 'या आठवड्यात नवीन',
    settings_unverified: 'असत्यापित',
    admin_pendingCategories: '🗂️ प्रलंबित श्रेणी',
    admin_approve: 'मंजूर करा',
    admin_reject: 'नाकारा',
    admin_noPendingCategories: 'कोणतीही प्रलंबित श्रेणी नाही',
    settings_vendorVerification: 'विक्रेता सत्यापन',
    settings_unverifiedFirst: 'असत्यापित विक्रेते आधी दिसतील.',
    settings_searchPlaceholder: 'नाव, दुकान, फोनने शोधा...',
    settings_noVendorsFound: 'कोणताही विक्रेता सापडला नाही.',
    settings_live: 'लाइव्ह',
    settings_btnLoading: '...',
    settings_verified: 'सत्यापित',
    settings_trustSecurity: 'विश्वास आणि सुरक्षा',
    settings_dbConnected: 'डेटाबेस: जोडलेले आणि सुरक्षित',
    settings_tlsNote: 'सर्व डेटा TLS द्वारे पाठवला जातो आणि row-level security ने सुरक्षित आहे.',
    settings_appName: 'आसपास प्रो',
    settings_appTagline: 'मदत, तुमच्या आसपास. आत्ता.',
    settings_version: 'आवृत्ती 1.0.0 · भारतासाठी बनवले',
    settings_copyright: '© 2026 आसपास प्रो',
    settings_devMenu: 'डेव्हलपर मेनू',
    settings_hideDevMenu: 'डेव्हलपर मेनू लपवा',
    settings_clearMyData: 'माझा डेटा साफ करा',
    settings_verifyVendor: 'विक्रेता सत्यापित करा',
    settings_check1: 'नोंदणीकृत फोनवर कॉल केला — व्यक्तीने उचलला',
    settings_check2: 'नाव कॉलमध्ये सांगितलेल्या नावाशी जुळते',
    settings_check3: 'विक्रेत्याला माहीत आहे की त्यांनी Aaspaas वर नोंदणी केली आहे',
    settings_check4: 'दुकान नोंदणीकृत ठिकाणी प्रत्यक्षात अस्तित्वात आहे',
    settings_check5: 'दुकानाचे नाव साइनबोर्ड / त्यांनी सांगितलेल्याशी जुळते',
    settings_check6: 'श्रेणी ते देत असलेल्या खऱ्या सेवेशी जुळते',
    settings_check7: 'सेवा मोड बरोबर आहे (help / delivery / appointment)',
    settings_check8: 'कोणताही डुप्लिकेट खाते सापडले नाही (समान फोन किंवा दुकान)',
    settings_check9: 'दुकानाचा फोटो अपलोड आहे आणि खरा वाटतो',
    settings_check10: 'UPI ID सत्यापित आहे (जर दिले असेल)',
    settings_check11: 'कोणतीही संशयास्पद क्रिया नाही (जलद ऑर्डर, बनावट नंबर)',
    settings_check12: 'विक्रेत्याला Aaspaas च्या वापर नियमांची माहिती आहे',
    settings_verifying: 'सत्यापित होत आहे...',
    settings_markVerified: '✅ सत्यापित करा',
    settings_cancel: 'रद्द करा',
    parchi_slotAsap: 'शक्य तितक्या लवकर',
    parchi_slotMorning: 'सकाळ (12 च्या आधी)',
    parchi_slotAfternoon: 'दुपार (12–4 वाजेपर्यंत)',
    parchi_slotEvening: 'संध्याकाळ (4 नंतर)',
    parchi_slotTomorrow: 'उद्या',
    parchi_errNoOrder: 'कृपया तुमचा ऑर्डर लिहा.',
    parchi_errNoAddress: 'कृपया डिलिव्हरी पत्ता टाका.',
    parchi_errNoDateTime: 'कृपया अपॉइंटमेंटची तारीख आणि वेळ निवडा.',
    parchi_locationComeToMe: ' [माझ्या घरी या]',
    parchi_locationVisitShop: ' [मी दुकानात येईन]',
    parchi_locationTbd: ' [ठिकाण ठरवायचे]',
    parchi_errCouldNotSend: 'ऑर्डर पाठवता आला नाही',
    parchi_toastBookingSuccess: '📅 बुकिंग विनंती पाठवली!',
    parchi_toastOrderSuccess: '✅ ऑर्डर पाठवला! ते लवकरच पाहतील.',
    parchi_slotAsapEmoji: '🚀 शक्य तितक्या लवकर',
    parchi_slotMorningEmoji: '🌅 सकाळ (12 च्या आधी)',
    parchi_slotAfternoonEmoji: '🌞 दुपार (12–4 वाजेपर्यंत)',
    parchi_slotEveningEmoji: '🌆 संध्याकाळ (4 नंतर)',
    parchi_slotTomorrowEmoji: '📅 उद्या',
    parchi_titleBook: 'बुकिंग: ',
    parchi_titleOrder: 'ऑर्डर: ',
    parchi_onlineBooking: '🟢 ऑनलाइन — बुकिंग लवकरच पुष्टी होईल',
    parchi_offlineBooking: '⚫ ऑफलाइन — परत आल्यावर पुष्टी करतील',
    parchi_onlineOrder: '🟢 ऑनलाइन — लवकरच पाहतील',
    parchi_offlineOrder: '⚫ ऑफलाइन — परत आल्यावर पाहतील',
    parchi_vendorNotePrefix: '📌 ',
    parchi_deliveryAddress: 'डिलिव्हरी पत्ता',
    parchi_loadingAddresses: 'पत्ते लोड होत आहेत...',
    parchi_useDifferentAddress: '+ वेगळा पत्ता वापरा',
    parchi_addressPlaceholder: 'उदा. फ्लॅट 4B, ग्रीन पार्क, वॉटर टॅंकजवळ',
    parchi_saveAddress: 'पुढच्या वेळेसाठी हा पत्ता जतन करा',
    parchi_whereQuestion: '📍 कुठे?',
    parchi_locationComeToMeBtn: '🏠 माझ्याकडे या',
    parchi_locationVisitBtn: '🏪 मी येईन',
    parchi_locationDecideLater: '📞 नंतर ठरवू',
    parchi_whenAppt: '📅 कधी हवे आहेत?',
    parchi_dateLabel: 'तारीख',
    parchi_timeLabel: 'वेळ',
    parchi_whenDelivery: '🕐 कधी हवे?',
    parchi_orderLabel: 'तुमचा ऑर्डर',
    parchi_placeholderAppt: 'काही विशेष सांगायचे?\nउदा. फुल फेशियल, 2 जण, ग्राउंड फ्लोर',
    parchi_placeholderOrder: 'ऑर्डर लिहा...\nउदा. 1kg पीठ, 2 साबण, Colgate टूथपेस्ट',
    parchi_charSeparator: ' / ',
    parchi_cancellationAppt:
      'ℹ️ बुकिंगच्या दिवसाआधी मोफत रद्द. त्याच दिवशी बदल करायचे असल्यास आधी कॉल करा.',
    parchi_cancellationOrder:
      'ℹ️ हा ऑर्डर रद्द होऊ शकतो फक्त जर विक्रेत्याने अद्याप पाहिला नसेल.',
    parchi_btnConfirmBooking: '📅 बुकिंग पक्की करा',
    parchi_btnSendOrder: '📋 ऑर्डर पाठवा',
    parchi_btnCancel: 'रद्द करा',
    incoming_errCouldNotUpdate: 'ऑर्डर अपडेट होऊ शकला नाही',
    incoming_errCouldNotUpdateAppt: 'अपॉइंटमेंट अपडेट होऊ शकली नाही',
    incoming_apptConfirmed: '✅ अपॉइंटमेंट पक्की झाली!',
    incoming_apptDeclined: 'अपॉइंटमेंट नाकारली.',
    incoming_errCouldNotCancel: 'रद्द होऊ शकले नाही',
    incoming_bookingCancelled: 'बुकिंग रद्द झाली.',
    incoming_statusNew: 'नवीन',
    incoming_statusSeen: 'पाहिले',
    incoming_statusDone: 'पूर्ण ✅',
    incoming_heading: '📋 येणारे ऑर्डर',
    incoming_unreadCap: '99+',
    incoming_empty: 'अद्याप कोणताही ऑर्डर नाही!',
    incoming_addressPrefix: '📍 ',
    incoming_slotPrefix: '🕐 ',
    incoming_locationComeToYou: '🏠 तुमच्याकडे येतील',
    incoming_locationVisitShop: '🏪 तुमच्या दुकानात येतील',
    incoming_locationTbd: '📞 ठिकाण ठरवायचे आहे',
    incoming_apptAround: '📅 साधारण ',
    incoming_btnConfirm: '✅ पुष्टी करा',
    incoming_btnDecline: '❌ नकार द्या',
    incoming_bannerConfirmed: '✅ अपॉइंटमेंट पक्की',
    incoming_bannerDeclined: '❌ अपॉइंटमेंट नाकारली',
    incoming_cancelAppt: 'अपॉइंटमेंट रद्द करा',
    incoming_sameDayWarning: '⚠️ त्याच दिवशी रद्द — आधी ग्राहकाला कॉल करा',
    incoming_callThenCancel: '📞 रद्द करण्यासाठी AI-Bridge शी जोडा',
    incoming_callDone: '✅ कॉल झाली — आता रद्द करू शकता',
    incoming_callBridge: '📞 AI-Bridge शी जोडा',
    incoming_saving: 'जतन होत आहे…',
    incoming_markDone: '✅ पूर्ण करा',
    incoming_btnAccept: '✅ स्वीकारा',
    status_accepted: 'विक्रेत्याने स्वीकारले — मार्गावर',
    order_already_taken: 'हा ऑर्डर दुसऱ्या विक्रेत्याने आधीच स्वीकारला',
    cancelOrder: 'ऑर्डर रद्द करा',
    cancelReason: 'रद्द का कारण?',
    confirmCancel: 'रद्द करा',
    orderCancelled: 'ऑर्डर रद्द झाला',
    other: 'इतर',
    cancelReasonPlaceholder: 'कारण लिहा...',
    editOrder: 'ऑर्डर बदला',
    saveChanges: 'बदल सेव्ह करा',
    orderUpdated: 'ऑर्डर अपडेट झाला',
    vendorSeenWarning:
      'विक्रेत्याने हा ऑर्डर पाहिला आहे. बदलाची सूचना त्यांना मिळेल.',
    rating_errCouldNotSave: 'रेटिंग जतन होऊ शकली नाही',
    rating_errCouldNotSaveFeedback: 'अभिप्राय जतन होऊ शकला नाही',
    rating_heading: 'तुमचा ऑर्डर कसा होता?',
    rating_btnDelivered: '📦 वेळेवर डिलिव्हर झाले',
    rating_btnHelped: '✅ त्यांनी मला मदत केली',
    rating_btnIssue: '⚠️ एक समस्या होती',
    rating_helperText: 'बंद करण्यासाठी अभिप्राय द्या',
  },
} as const;

export type StringKeys = keyof typeof strings.en;
