-- Seed categories from PROD (27 rows). ON CONFLICT DO NOTHING for idempotent apply.
-- Skips rows when label already exists (TEST may have same labels with different ids).

INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT '2a455188-44e2-4e9d-9992-54c8b3668675', 'Beautician', '💄', 'appointment', true, 1, '2026-05-17T08:50:49.660015+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Beautician') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT 'a899ed3e-f970-48a2-a597-7b38064cb9f9', 'Grocery Store', '🛒', 'delivery', true, 1, '2026-05-17T08:50:49.660015+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Grocery Store') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT '65a0fdb1-ce3e-4037-9c4d-eeccc78963cb', 'Mechanic', '🔧', 'help', true, 1, '2026-05-17T08:50:49.660015+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Mechanic') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT '3967b2a0-47c9-4695-b90b-599dc8a9c7c0', 'Tailor', '🧵', 'appointment', true, 2, '2026-05-17T08:50:49.660015+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Tailor') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT '06c85a2c-d14b-41aa-8f01-5c0a3317f74e', 'Ambulance', '🚑', 'help', true, 2, '2026-05-17T08:50:49.660015+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Ambulance') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT '1e0e1d4c-4f95-4c85-bd1c-c33cde2f0221', 'Pharmacy', '💊', 'delivery', true, 2, '2026-05-17T08:50:49.660015+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Pharmacy') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT '95de52e3-c0aa-44d1-839c-38007177d10e', 'Cook', '👨‍🍳', 'appointment', true, 3, '2026-05-17T08:50:49.660015+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Cook') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT '0a80f9c9-8349-4287-ad66-cd68b0f360fb', 'Towing', '🚛', 'help', true, 3, '2026-05-17T08:50:49.660015+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Towing') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT '5e25329a-dd5b-46ec-b4cd-60c0accc7542', 'Tyre Service', '⚙️', 'help', true, 4, '2026-05-17T08:50:49.660015+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Tyre Service') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT 'afce3c0d-1f35-40eb-9e17-dea9f974e7fa', 'Barber', '💈', 'appointment', true, 4, '2026-05-17T08:50:49.660015+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Barber') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT '6caddb4b-7650-4a63-a0e8-f042c088b7c8', 'Key Maker', '🔑', 'help', true, 5, '2026-05-17T08:50:49.660015+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Key Maker') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT '52a22d80-a747-4e41-afa3-3b67997c9679', 'Electrician', '💡', 'help', true, 6, '2026-05-17T08:50:49.660015+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Electrician') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT 'd1d81455-38f3-48c5-afec-63af4e8ecd24', 'Plumber', '🚰', 'help', true, 7, '2026-05-17T08:50:49.660015+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Plumber') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT 'c2de7dfc-71a9-40e6-8c5e-d146a834c2c4', 'Nursing', '🩺', 'help', true, 8, '2026-05-17T08:50:49.660015+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Nursing') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT 'd3a140dc-f8fc-431d-a287-9ba5dbfce724', 'Security', '🛡️', 'help', true, 9, '2026-05-17T08:50:49.660015+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Security') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT 'ed8f2ae0-da7b-4634-ac13-19ccf829e448', 'Therapist', '🧘', 'help', true, 10, '2026-05-17T08:50:49.660015+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Therapist') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT 'c9bf9965-e527-45d7-bb2c-f22fa6e38ba7', 'Fire Brigade', '🔥', 'help', true, 11, '2026-05-17T08:50:49.660015+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Fire Brigade') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT 'bf3286ce-e4bd-4a5c-ba15-47400043b6e9', 'Gym', '🏋️', 'appointment', true, 20, '2026-05-30T11:38:07.473709+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Gym') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT '43d950d9-81cf-4d37-a237-f417a8ed1202', 'Yoga', '🧘', 'appointment', true, 21, '2026-05-30T11:38:07.473709+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Yoga') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT 'c2c80c97-5205-4cdb-89e4-6d42d37b0f7c', 'Tutor', '📚', 'appointment', true, 22, '2026-05-30T11:38:07.473709+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Tutor') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT '082861f1-7d9d-4352-bfc6-b37032eb528d', 'Bakery', '🥐', 'delivery', true, 25, '2026-05-30T11:38:07.473709+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Bakery') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT 'c3005771-ff5e-4e55-8fbd-e066cc829e16', 'Dairy', '🥛', 'delivery', true, 26, '2026-05-30T11:38:07.473709+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Dairy') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT 'd0af4c84-abc0-43b4-adfc-abb6b7bc6747', 'Carpenter', '🔨', 'help', true, 27, '2026-05-30T11:38:07.473709+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Carpenter') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT 'e1ab5f6a-47f2-4185-8fb8-b670e9d2ed33', 'Laundry', '👕', 'help', true, 31, '2026-05-30T11:38:07.473709+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Laundry') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT '00a33463-823f-48b2-a63e-7135f95ec78d', 'Maid', '🧹', 'help', true, 32, '2026-05-30T11:38:07.473709+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Maid') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT '43927017-54a5-4654-bd46-84c837b58bef', 'Painter', '🎨', 'help', true, 34, '2026-05-30T11:38:07.473709+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Painter') ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, emoji, service_mode, is_active, sort_order, created_at, pending_review, suggested_by_vendor_id, ai_confidence, ai_reasoning, status, suggestion_count, ai_confidence_score) SELECT '9404dd1d-82fd-4836-93f8-e188f23a9d9b', 'Driver', '🚗', 'delivery', true, 35, '2026-05-30T11:38:07.473709+00:00', false, NULL, NULL, NULL, 'active', 0, NULL WHERE NOT EXISTS (SELECT 1 FROM categories WHERE label = 'Driver') ON CONFLICT (id) DO NOTHING;
